
docker_skill = {
  "skill_id": "docker",
  "skill_name": "Docker",
  "category": "devops_cloud",
  "total_questions": 10,
  "levels": {
    "beginner": [
      {"question_id":"docker_beg_001","type":"mcq","question":"What does a Dockerfile define?","options":["A running container","Instructions to build a Docker image","A Docker network","A volume mount"],"correct_answer":1,"explanation":"A Dockerfile is a text file with ordered instructions to build a Docker image. FROM sets the base image, RUN executes commands, COPY adds files, CMD sets the default startup command.","difficulty_score":1,"time_seconds":30,"tags":["dockerfile","images","basics"],"prerequisites":[],"common_mistakes":["Confusing Dockerfile with docker-compose.yml","Confusing image with container"],"learning_resources":["https://docs.docker.com/engine/reference/builder/"],"real_world_context":"Every Docker-based deployment starts with a well-written Dockerfile."},
      {"question_id":"docker_beg_002","type":"true_false","question":"A Docker container retains data written to its filesystem after the container is removed.","correct_answer":False,"explanation":"Container filesystems are ephemeral — data written inside is lost when the container is removed. Use Docker volumes or bind mounts to persist data beyond the container lifecycle.","difficulty_score":2,"time_seconds":30,"tags":["volumes","persistence","containers"],"prerequisites":["docker_beg_001"],"common_mistakes":["Writing data inside containers without volumes"],"learning_resources":["https://docs.docker.com/storage/volumes/"],"real_world_context":"Database containers must use volumes or all data is lost on restart."},
      {"question_id":"docker_beg_003","type":"mcq","question":"Which command runs a container in detached (background) mode?","options":["docker run -i","docker run -d","docker run -t","docker run -rm"],"correct_answer":1,"explanation":"docker run -d starts a container in detached mode, running in the background and printing the container ID. -i is interactive, -t allocates a pseudo-TTY, --rm removes the container on exit.","difficulty_score":2,"time_seconds":30,"tags":["docker_run","cli","detached"],"prerequisites":["docker_beg_001"],"common_mistakes":["Confusing -d with -i or -t flags"],"learning_resources":["https://docs.docker.com/engine/reference/commandline/run/"],"real_world_context":"-d is used for all production service containers so they run persistently."},
      {"question_id":"docker_beg_004","type":"true_false","question":"Docker images are built from bottom to top, and each instruction creates a new layer.","correct_answer":True,"explanation":"Each Dockerfile instruction (RUN, COPY, ADD) creates an immutable layer. Docker caches layers and only rebuilds from the first changed instruction, making builds fast for unchanged layers.","difficulty_score":3,"time_seconds":30,"tags":["image_layers","caching","dockerfile"],"prerequisites":["docker_beg_001"],"common_mistakes":["Putting frequently-changing instructions early, busting cache"],"learning_resources":["https://docs.docker.com/develop/develop-images/dockerfile_best-practices/"],"real_world_context":"Ordering Dockerfile instructions by change frequency is a key optimisation."}
    ],
    "intermediate": [
      {"question_id":"docker_int_001","type":"scenario","question":"A Docker image for a Python app is 2.1 GB. What is the BEST strategy to reduce its size?","options":["Use ZIP compression","Use a slim/alpine base image and multi-stage builds","Remove the Dockerfile comments","Use EXPOSE to limit ports"],"correct_answer":1,"explanation":"Multi-stage builds compile code in a full image then copy only the artefacts into a minimal runtime image. Alpine-based images are 5-10x smaller than Debian-based. Together these often reduce images from GB to MB.","difficulty_score":5,"time_seconds":75,"tags":["image_optimization","multi_stage","alpine"],"prerequisites":["docker_beg_004"],"common_mistakes":["Installing dev tools in the final image","Not cleaning pip cache after install"],"learning_resources":["https://docs.docker.com/develop/develop-images/multistage-build/"],"real_world_context":"Smaller images reduce registry storage costs and deployment time."},
      {"question_id":"docker_int_002","type":"mcq","question":"What is the difference between COPY and ADD in a Dockerfile?","options":["No difference","ADD can fetch URLs and extract tar archives; COPY only copies local files","COPY is faster than ADD","ADD requires root privileges"],"correct_answer":1,"explanation":"COPY simply copies local files into the image. ADD has extra features: it can download files from URLs and auto-extract tar archives. Best practice is to use COPY unless the extra ADD features are specifically needed.","difficulty_score":5,"time_seconds":45,"tags":["dockerfile","COPY","ADD"],"prerequisites":["docker_beg_001"],"common_mistakes":["Using ADD for simple file copies (obscures intent)"],"learning_resources":["https://docs.docker.com/engine/reference/builder/#copy"],"real_world_context":"COPY is preferred in almost all Dockerfiles to keep intent explicit."},
      {"question_id":"docker_int_003","type":"code_debugging","question":"A containerised app cannot connect to a sibling container. Both are on the default bridge network. What is wrong?\n\nApp uses: requests.get('http://localhost:5432')","options":["5432 is reserved","localhost in a container refers to the container itself, not siblings","TCP is not supported in Docker","Container networking is disabled by default"],"correct_answer":1,"explanation":"Each container has its own network namespace. localhost inside a container points to that container, not to sibling containers. Use the container name as the hostname when both are on the same Docker network.","difficulty_score":6,"time_seconds":75,"tags":["networking","container_communication","DNS"],"prerequisites":["docker_int_001"],"common_mistakes":["Using localhost/127.0.0.1 to reach other containers"],"learning_resources":["https://docs.docker.com/network/bridge/"],"real_world_context":"docker-compose sets up a default network where service names are DNS hostnames."},
      {"question_id":"docker_int_004","type":"mcq","question":"What does the --no-cache flag do in docker build?","options":["Builds without internet access","Forces Docker to rebuild all layers ignoring the layer cache","Disables build logging","Removes the image after build"],"correct_answer":1,"explanation":"--no-cache forces Docker to execute every Dockerfile instruction fresh, ignoring cached layers. Useful when you suspect cached layers contain stale dependencies or to verify a clean build.","difficulty_score":5,"time_seconds":45,"tags":["build","caching","dockerfile"],"prerequisites":["docker_beg_004"],"common_mistakes":["Using --no-cache in production CI slowing builds unnecessarily"],"learning_resources":["https://docs.docker.com/engine/reference/commandline/build/"],"real_world_context":"--no-cache is used in security scanning workflows to catch updated base image vulnerabilities."}
    ],
    "advanced": [
      {"question_id":"docker_adv_001","type":"scenario","question":"A container running as root writes files to a volume. The host sees them as root-owned, blocking a non-root host process. What is the fix?","options":["Use chmod 777 on the volume","Run container as a non-root user with the same UID as the host process","Use a tmpfs volume","Remove volume permissions"],"correct_answer":1,"explanation":"Docker containers inherit file ownership based on UIDs. Running as a non-root user with USER in the Dockerfile and matching the host UID ensures volume files have the correct ownership without privilege escalation.","difficulty_score":8,"time_seconds":120,"tags":["security","user_namespaces","volumes","UID"],"prerequisites":["docker_int_001"],"common_mistakes":["Running all containers as root for convenience"],"learning_resources":["https://docs.docker.com/engine/security/userns-remap/"],"real_world_context":"Root container files block CI pipelines that run as non-root users."},
      {"question_id":"docker_adv_002","type":"mcq","question":"What is a distroless Docker image and its primary benefit?","options":["An image with no networking","An image containing only the application and its runtime, no OS shell or package manager","An image without a base OS layer","An image with no file system"],"correct_answer":1,"explanation":"Distroless images (e.g., Google's gcr.io/distroless) contain only the app and runtime libraries — no shell, no package manager. This dramatically reduces the attack surface because there are no tools for attackers to exploit.","difficulty_score":8,"time_seconds":120,"tags":["security","distroless","attack_surface"],"prerequisites":["docker_adv_001"],"common_mistakes":["Not knowing distroless images exist","Thinking minimal and distroless are the same"],"learning_resources":["https://github.com/GoogleContainerTools/distroless"],"real_world_context":"Distroless is the gold standard for production container security hardening."}
    ]
  }
}

k8s_skill = {
  "skill_id": "kubernetes",
  "skill_name": "Kubernetes",
  "category": "devops_cloud",
  "total_questions": 10,
  "levels": {
    "beginner": [
      {"question_id":"k8s_beg_001","type":"mcq","question":"What is the smallest deployable unit in Kubernetes?","options":["Container","Pod","Node","Deployment"],"correct_answer":1,"explanation":"A Pod is the smallest deployable unit in Kubernetes. It can contain one or more containers that share the same network namespace and storage. Pods are ephemeral; Deployments manage their lifecycle.","difficulty_score":1,"time_seconds":30,"tags":["pods","fundamentals","kubernetes"],"prerequisites":[],"common_mistakes":["Thinking a container is the basic unit in Kubernetes"],"learning_resources":["https://kubernetes.io/docs/concepts/workloads/pods/"],"real_world_context":"Every workload in Kubernetes runs inside a Pod, even if it is a single container."},
      {"question_id":"k8s_beg_002","type":"true_false","question":"A Kubernetes Service provides a stable network endpoint for a dynamic set of Pods.","correct_answer":True,"explanation":"Pods have ephemeral IP addresses that change on restart. A Service provides a stable virtual IP and DNS name, load-balancing traffic across matching Pods using label selectors.","difficulty_score":2,"time_seconds":30,"tags":["services","networking","pods"],"prerequisites":["k8s_beg_001"],"common_mistakes":["Connecting directly to Pod IPs instead of using Services"],"learning_resources":["https://kubernetes.io/docs/concepts/services-networking/service/"],"real_world_context":"Services are how microservices discover and communicate with each other in Kubernetes."},
      {"question_id":"k8s_beg_003","type":"mcq","question":"What Kubernetes object manages rolling updates and rollbacks for stateless applications?","options":["StatefulSet","DaemonSet","Deployment","Job"],"correct_answer":2,"explanation":"Deployments manage ReplicaSets for stateless applications, providing rolling updates with automatic rollback on failure. StatefulSets are for stateful apps; DaemonSets run one Pod per node; Jobs run to completion.","difficulty_score":2,"time_seconds":30,"tags":["deployments","rollouts","stateless"],"prerequisites":["k8s_beg_001"],"common_mistakes":["Using StatefulSet for stateless apps"],"learning_resources":["https://kubernetes.io/docs/concepts/workloads/controllers/deployment/"],"real_world_context":"Deployments power zero-downtime rolling releases in production Kubernetes clusters."},
      {"question_id":"k8s_beg_004","type":"true_false","question":"A Kubernetes ConfigMap stores sensitive data like passwords and API keys securely.","correct_answer":False,"explanation":"ConfigMaps store non-sensitive configuration data. Secrets are the Kubernetes object for sensitive data, though they are only base64-encoded by default. For true security, use an external vault (Vault, AWS Secrets Manager) with the secrets operator.","difficulty_score":3,"time_seconds":30,"tags":["configmap","secrets","security"],"prerequisites":["k8s_beg_001"],"common_mistakes":["Putting passwords in ConfigMaps","Thinking Secrets are encrypted by default"],"learning_resources":["https://kubernetes.io/docs/concepts/configuration/secret/"],"real_world_context":"Misusing ConfigMap for secrets is a common security misconfiguration found in audits."}
    ],
    "intermediate": [
      {"question_id":"k8s_int_001","type":"scenario","question":"Pods are being OOMKilled repeatedly. What Kubernetes configuration prevents this and provides scheduling hints?","options":["Pod Anti-Affinity","Resource requests and limits","PodDisruptionBudget","HorizontalPodAutoscaler"],"correct_answer":1,"explanation":"Resource requests tell the scheduler how much memory to reserve for the Pod. Resource limits cap what the Pod can use. Without limits, a Pod can consume all node memory, causing OOMKill for itself or other Pods.","difficulty_score":5,"time_seconds":75,"tags":["resources","OOMKill","limits","requests"],"prerequisites":["k8s_beg_003"],"common_mistakes":["Deploying without resource limits","Setting limits too low causing constant OOMKill"],"learning_resources":["https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/"],"real_world_context":"Missing resource limits cause noisy-neighbour OOM incidents in shared clusters."},
      {"question_id":"k8s_int_002","type":"mcq","question":"What does a Kubernetes Ingress resource do?","options":["Manages internal service-to-service traffic","Exposes HTTP/HTTPS routes from outside the cluster to services inside","Controls Pod-to-Pod network policies","Manages TLS certificates for Pods"],"correct_answer":1,"explanation":"An Ingress exposes HTTP/HTTPS routes to services inside the cluster, supporting host-based and path-based routing. It requires an Ingress controller (e.g., NGINX, Traefik) to be installed in the cluster.","difficulty_score":5,"time_seconds":60,"tags":["ingress","routing","HTTP","networking"],"prerequisites":["k8s_beg_002"],"common_mistakes":["Confusing Ingress with LoadBalancer Service type","Forgetting to install an Ingress controller"],"learning_resources":["https://kubernetes.io/docs/concepts/services-networking/ingress/"],"real_world_context":"Ingress is the standard way to route external traffic to multiple services in a cluster."},
      {"question_id":"k8s_int_003","type":"code_debugging","question":"A Deployment has 3 replicas and a RollingUpdate strategy with maxUnavailable=0. After an update, all Pods are Pending. Why?","options":["maxUnavailable=0 is invalid","New Pods cannot be scheduled — likely insufficient cluster resources","Rolling update does not work with 3 replicas","Pending means the update succeeded"],"correct_answer":1,"explanation":"maxUnavailable=0 requires new Pods to be Running before old ones terminate. If the cluster lacks CPU/memory for even one new Pod, the rollout stalls with Pods in Pending state. Scale the cluster or reduce resource requests.","difficulty_score":6,"time_seconds":90,"tags":["rollingupdate","scheduling","resources","pending"],"prerequisites":["k8s_int_001"],"common_mistakes":["Thinking Pending means a networking issue","Not checking cluster resource capacity before deploying"],"learning_resources":["https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-update-deployment"],"real_world_context":"Stalled rollouts due to resource constraints are a common production incident."},
      {"question_id":"k8s_int_004","type":"mcq","question":"What is a Kubernetes liveness probe used for?","options":["Checking if the Pod is ready to receive traffic","Restarting a container that is stuck or deadlocked","Monitoring Pod resource usage","Validating YAML manifests"],"correct_answer":1,"explanation":"A liveness probe checks if a container is still healthy and running correctly. If it fails, Kubernetes restarts the container. A readiness probe determines if the Pod should receive traffic — these are separate concerns.","difficulty_score":5,"time_seconds":60,"tags":["probes","liveness","health_check"],"prerequisites":["k8s_beg_003"],"common_mistakes":["Confusing liveness and readiness probes","Using the same endpoint for both probes"],"learning_resources":["https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/"],"real_world_context":"Liveness probes automatically recover deadlocked processes without manual intervention."}
    ],
    "advanced": [
      {"question_id":"k8s_adv_001","type":"scenario","question":"A stateful database cluster on Kubernetes needs stable network identities and ordered Pod startup. Which object is correct?","options":["Deployment","StatefulSet","DaemonSet","CronJob"],"correct_answer":1,"explanation":"StatefulSets provide stable, unique Pod names (pod-0, pod-1), stable persistent volume claims, and ordered startup/shutdown. These are required for databases like Cassandra or Zookeeper that depend on node identity.","difficulty_score":8,"time_seconds":120,"tags":["StatefulSet","databases","stateful","persistence"],"prerequisites":["k8s_int_004"],"common_mistakes":["Using Deployment for clustered databases losing identity on rescheduling"],"learning_resources":["https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/"],"real_world_context":"StatefulSets are the Kubernetes mechanism for running distributed databases in production."},
      {"question_id":"k8s_adv_002","type":"mcq","question":"What is a Kubernetes Operator and what problem does it solve?","options":["A Kubernetes admin role","A custom controller that extends Kubernetes to manage complex stateful applications using domain-specific knowledge","A StatefulSet with extra features","A monitoring sidecar"],"correct_answer":1,"explanation":"An Operator is a custom controller that watches Custom Resources and encodes operational knowledge (backup, failover, scaling) for complex stateful apps. It automates tasks that would otherwise require a human operator.","difficulty_score":9,"time_seconds":120,"tags":["operators","CRD","custom_controllers","advanced"],"prerequisites":["k8s_adv_001"],"common_mistakes":["Thinking Operators are only for databases","Confusing Operator with Helm chart"],"learning_resources":["https://operatorhub.io/"],"real_world_context":"Operators manage production databases (e.g., Postgres Operator, Kafka Strimzi) on Kubernetes."}
    ]
  }
}

aws_skill = {
  "skill_id": "aws_cloud",
  "skill_name": "AWS / Cloud",
  "category": "devops_cloud",
  "total_questions": 10,
  "levels": {
    "beginner": [
      {"question_id":"aws_beg_001","type":"mcq","question":"Which AWS service provides object storage?","options":["EC2","RDS","S3","ECS"],"correct_answer":2,"explanation":"S3 (Simple Storage Service) provides scalable object storage. EC2 provides virtual machines, RDS provides managed relational databases, ECS runs Docker containers.","difficulty_score":1,"time_seconds":30,"tags":["S3","storage","AWS_basics"],"prerequisites":[],"common_mistakes":["Confusing S3 with EBS (block storage)"],"learning_resources":["https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html"],"real_world_context":"S3 is the backbone of virtually every AWS architecture for storing files, backups, and static assets."},
      {"question_id":"aws_beg_002","type":"true_false","question":"AWS IAM Roles are more secure than IAM Users with access keys for granting EC2 instances access to AWS services.","correct_answer":True,"explanation":"IAM Roles use temporary credentials automatically rotated by AWS STS. IAM User access keys are long-lived and frequently leaked in code. Best practice is always to use Roles for services, not static keys.","difficulty_score":2,"time_seconds":30,"tags":["IAM","security","EC2","roles"],"prerequisites":["aws_beg_001"],"common_mistakes":["Embedding IAM user access keys in EC2 instance environment variables"],"learning_resources":["https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html"],"real_world_context":"IAM Role misuse is in the top 5 AWS security incidents causing data breaches."},
      {"question_id":"aws_beg_003","type":"mcq","question":"What is the primary purpose of AWS Auto Scaling?","options":["Automatically back up data","Automatically add or remove EC2 instances based on demand","Replicate S3 buckets across regions","Monitor application logs"],"correct_answer":1,"explanation":"Auto Scaling automatically adjusts EC2 capacity in response to demand, scaling out under load and scaling in during quiet periods. This optimises cost while maintaining performance.","difficulty_score":2,"time_seconds":30,"tags":["auto_scaling","EC2","cost_optimization"],"prerequisites":["aws_beg_001"],"common_mistakes":["Confusing Auto Scaling with load balancing"],"learning_resources":["https://docs.aws.amazon.com/autoscaling/ec2/userguide/what-is-amazon-ec2-auto-scaling.html"],"real_world_context":"Auto Scaling is essential for cost-effective handling of traffic spikes."},
      {"question_id":"aws_beg_004","type":"true_false","question":"AWS Lambda functions can run indefinitely — there is no timeout limit.","correct_answer":False,"explanation":"AWS Lambda has a maximum execution timeout of 15 minutes (900 seconds). Long-running workloads should use ECS, Fargate, or EC2 instead. Lambda is designed for short, event-driven functions.","difficulty_score":2,"time_seconds":30,"tags":["Lambda","serverless","limits"],"prerequisites":[],"common_mistakes":["Using Lambda for long-running batch jobs exceeding 15 minutes"],"learning_resources":["https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html"],"real_world_context":"Lambda timeout limits often surprise teams migrating long-running jobs to serverless."}
    ],
    "intermediate": [
      {"question_id":"aws_int_001","type":"scenario","question":"An API receives 10,000 requests/second in bursts. The backend RDS database becomes a bottleneck. What AWS service mitigates this?","options":["Increase RDS instance size","Add ElastiCache (Redis) as a caching layer","Use multiple S3 buckets","Switch to DynamoDB immediately"],"correct_answer":1,"explanation":"ElastiCache (Redis) caches hot query results, serving them from RAM without hitting RDS. This reduces database load dramatically during bursts. Scaling RDS is expensive and slower to provision.","difficulty_score":5,"time_seconds":75,"tags":["ElastiCache","Redis","caching","RDS"],"prerequisites":["aws_beg_001"],"common_mistakes":["Scaling the database vertically before adding caching"],"learning_resources":["https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/WhatIs.html"],"real_world_context":"Redis caching is a standard AWS architecture pattern for high-traffic read-heavy APIs."},
      {"question_id":"aws_int_002","type":"mcq","question":"What is the difference between SQS and SNS?","options":["No difference","SQS is a message queue (pull); SNS is a pub/sub notification service (push)","SNS stores messages; SQS does not","SQS is only for email notifications"],"correct_answer":1,"explanation":"SQS is a distributed pull-based message queue for decoupling components. SNS is a pub/sub service that pushes messages to multiple subscribers simultaneously. They are often combined: SNS fans out to multiple SQS queues.","difficulty_score":5,"time_seconds":60,"tags":["SQS","SNS","messaging","pub_sub"],"prerequisites":["aws_beg_003"],"common_mistakes":["Confusing push and pull messaging models"],"learning_resources":["https://docs.aws.amazon.com/sns/latest/dg/sns-sqs-as-subscriber.html"],"real_world_context":"SNS+SQS fanout is the standard AWS pattern for event-driven microservice architectures."},
      {"question_id":"aws_int_003","type":"code_debugging","question":"An S3 static website returns 403 on all files despite public bucket policy. What is most likely wrong?","options":["S3 does not support static websites","Block Public Access settings are enabled at account or bucket level","Files must be in a 'public' folder","CloudFront must be used instead of S3"],"correct_answer":1,"explanation":"S3 Block Public Access settings (at account or bucket level) override bucket policies, blocking all public access. This setting must be disabled before bucket policies allowing public read take effect.","difficulty_score":5,"time_seconds":60,"tags":["S3","permissions","Block_Public_Access","static_website"],"prerequisites":["aws_beg_002"],"common_mistakes":["Setting bucket policy without disabling Block Public Access"],"learning_resources":["https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html"],"real_world_context":"Block Public Access is a common gotcha when deploying React SPAs to S3."},
      {"question_id":"aws_int_004","type":"mcq","question":"What is AWS VPC and why is it used?","options":["A virtual private server","An isolated virtual network in AWS where you control IP addressing, routing, and security","A content delivery network","A managed Kubernetes service"],"correct_answer":1,"explanation":"A VPC (Virtual Private Cloud) is a logically isolated network segment in AWS. It gives full control over subnets, route tables, internet gateways, and security groups, enabling secure multi-tier architectures.","difficulty_score":5,"time_seconds":60,"tags":["VPC","networking","security","AWS"],"prerequisites":["aws_beg_002"],"common_mistakes":["Running all resources in the default VPC without isolation"],"learning_resources":["https://docs.aws.amazon.com/vpc/latest/userguide/what-is-amazon-vpc.html"],"real_world_context":"VPC design is the first step in any secure AWS architecture review."}
    ],
    "advanced": [
      {"question_id":"aws_adv_001","type":"scenario","question":"A multi-region AWS app needs active-active failover with sub-second DNS switching. Which service combination achieves this?","options":["Route53 with Latency routing + health checks + Global Accelerator","CloudFront + S3 + Lambda@Edge","ALB + Auto Scaling + CloudWatch","API Gateway + Lambda + DynamoDB"],"correct_answer":0,"explanation":"Route53 health checks detect regional failures and reroute traffic within 60 seconds. AWS Global Accelerator provides anycast IPs and routes at the network layer for sub-second failover, independent of DNS TTLs.","difficulty_score":9,"time_seconds":120,"tags":["multi_region","Route53","Global_Accelerator","failover"],"prerequisites":["aws_int_004"],"common_mistakes":["Relying on CloudFront alone for active-active failover","Not accounting for DNS TTL propagation delay"],"learning_resources":["https://docs.aws.amazon.com/global-accelerator/latest/dg/introduction-how-it-works.html"],"real_world_context":"Global Accelerator is used by Stripe and Airbnb for multi-region active-active deployments."},
      {"question_id":"aws_adv_002","type":"mcq","question":"What is the AWS Shared Responsibility Model?","options":["AWS is responsible for all security aspects","Customers are responsible for all security","AWS secures the cloud infrastructure; customers secure what is deployed in the cloud","Responsibility is shared 50/50 for all layers"],"correct_answer":2,"explanation":"AWS is responsible for the security OF the cloud (hardware, data centres, managed service security). Customers are responsible for security IN the cloud: data encryption, IAM configuration, OS patching, and application security.","difficulty_score":7,"time_seconds":90,"tags":["shared_responsibility","security","compliance","AWS"],"prerequisites":["aws_int_002"],"common_mistakes":["Assuming AWS handles all security including data encryption","Not patching OS on EC2 instances"],"learning_resources":["https://aws.amazon.com/compliance/shared-responsibility-model/"],"real_world_context":"The shared responsibility model is foundational for AWS security certifications and compliance audits."}
    ]
  }
}

ml_skill = {
  "skill_id": "ml_fundamentals",
  "skill_name": "ML Fundamentals",
  "category": "machine_learning",
  "total_questions": 10,
  "levels": {
    "beginner": [
      {"question_id":"ml_beg_001","type":"mcq","question":"What is the difference between supervised and unsupervised learning?","options":["Supervised uses more data","Supervised learns from labelled data; unsupervised finds patterns in unlabelled data","Unsupervised is always more accurate","No practical difference"],"correct_answer":1,"explanation":"Supervised learning trains on labelled input-output pairs to predict labels for new inputs. Unsupervised learning discovers structure in unlabelled data, e.g., clustering or dimensionality reduction.","difficulty_score":1,"time_seconds":30,"tags":["supervised","unsupervised","fundamentals"],"prerequisites":[],"common_mistakes":["Thinking unsupervised means less effective"],"learning_resources":["https://developers.google.com/machine-learning/crash-course"],"real_world_context":"Choosing the right learning paradigm is the first decision in any ML project."},
      {"question_id":"ml_beg_002","type":"true_false","question":"A model with 99% training accuracy and 60% test accuracy is underfitting.","correct_answer":False,"explanation":"High training accuracy but low test accuracy indicates overfitting — the model memorised training data but failed to generalise. Underfitting is when both training and test accuracy are low.","difficulty_score":2,"time_seconds":30,"tags":["overfitting","underfitting","generalisation"],"prerequisites":["ml_beg_001"],"common_mistakes":["Confusing overfitting and underfitting"],"learning_resources":["https://developers.google.com/machine-learning/crash-course/generalization/peril-of-overfitting"],"real_world_context":"Overfitting on training data is the most common failure mode in ML model development."},
      {"question_id":"ml_beg_003","type":"mcq","question":"What does the learning rate hyperparameter control in gradient descent?","options":["Number of training epochs","Size of each step taken toward the loss minimum","Number of features used","Batch size"],"correct_answer":1,"explanation":"The learning rate controls how large each gradient descent step is. Too large: overshoots and diverges. Too small: converges extremely slowly. Appropriate learning rate scheduling is a key hyperparameter tuning task.","difficulty_score":3,"time_seconds":45,"tags":["learning_rate","gradient_descent","optimization","hyperparameters"],"prerequisites":["ml_beg_001"],"common_mistakes":["Thinking a smaller learning rate is always better"],"learning_resources":["https://developers.google.com/machine-learning/crash-course/reducing-loss/learning-rate"],"real_world_context":"Learning rate is the most impactful hyperparameter in neural network training."},
      {"question_id":"ml_beg_004","type":"true_false","question":"Cross-validation is used to evaluate a model's generalisation performance when data is limited.","correct_answer":True,"explanation":"K-fold cross-validation splits data into k folds, training on k-1 and validating on the remaining fold, rotating through all folds. It provides a robust performance estimate without sacrificing training data.","difficulty_score":3,"time_seconds":30,"tags":["cross_validation","evaluation","generalisation"],"prerequisites":["ml_beg_002"],"common_mistakes":["Using a single train-test split with small datasets leading to high variance estimates"],"learning_resources":["https://scikit-learn.org/stable/modules/cross_validation.html"],"real_world_context":"Cross-validation is standard practice for model selection in small-dataset ML projects."}
    ],
    "intermediate": [
      {"question_id":"ml_int_001","type":"mcq","question":"What does L2 regularisation (Ridge) do during model training?","options":["Randomly drops neurons","Adds the sum of squared weights to the loss, penalising large weights","Normalises input features","Reduces learning rate over time"],"correct_answer":1,"explanation":"L2 regularisation adds lambda * sum(w^2) to the loss function, penalising large weights and encouraging simpler models. This reduces overfitting by distributing weight across features instead of relying on a few large ones.","difficulty_score":5,"time_seconds":60,"tags":["regularisation","Ridge","overfitting","L2"],"prerequisites":["ml_beg_002"],"common_mistakes":["Confusing L1 (Lasso) and L2 (Ridge) effects"],"learning_resources":["https://developers.google.com/machine-learning/crash-course/regularization-for-simplicity/l2-regularization"],"real_world_context":"L2 regularisation is the default in most regression models through sklearn's Ridge class."},
      {"question_id":"ml_int_002","type":"scenario","question":"A binary classifier on a medical dataset achieves 98% accuracy, but all predictions are the negative class. What metric reveals this?","options":["Accuracy","F1-Score / Recall for positive class","AUC-ROC","Mean Squared Error"],"correct_answer":1,"explanation":"If 98% of samples are negative, predicting all negatives gives 98% accuracy but 0% recall on the positive class. F1-Score and Recall for the minority class expose this. Accuracy is misleading on imbalanced datasets.","difficulty_score":5,"time_seconds":75,"tags":["imbalanced_data","recall","F1_score","classification_metrics"],"prerequisites":["ml_beg_002"],"common_mistakes":["Using only accuracy for imbalanced classification tasks"],"learning_resources":["https://scikit-learn.org/stable/modules/model_evaluation.html"],"real_world_context":"Medical screening, fraud detection, and defect detection all have highly imbalanced classes."},
      {"question_id":"ml_int_003","type":"mcq","question":"What is feature importance in a Random Forest model?","options":["Number of features used","A measure of how much each feature contributes to reducing impurity across all trees","Correlation between features","Normalised feature values"],"correct_answer":1,"explanation":"Random Forest feature importance measures the average reduction in Gini impurity (or MSE) contributed by each feature across all trees. Higher importance = the feature is more useful for splitting nodes.","difficulty_score":5,"time_seconds":60,"tags":["random_forest","feature_importance","interpretability"],"prerequisites":["ml_int_001"],"common_mistakes":["Thinking feature importance equals correlation with the target"],"learning_resources":["https://scikit-learn.org/stable/auto_examples/ensemble/plot_forest_importances.html"],"real_world_context":"Feature importance is used to explain model decisions and reduce dimensionality."},
      {"question_id":"ml_int_004","type":"code_debugging","question":"A model trained on 2020 data deployed in 2024 shows degrading performance. What is this phenomenon?","options":["Overfitting","Data/concept drift","Underfitting","Label noise"],"correct_answer":1,"explanation":"Data drift occurs when the statistical distribution of input features changes over time. Concept drift occurs when the relationship between features and target changes. Both cause model performance to degrade in production after deployment.","difficulty_score":6,"time_seconds":60,"tags":["data_drift","concept_drift","MLOps","model_monitoring"],"prerequisites":["ml_int_002"],"common_mistakes":["Assuming a trained model stays accurate indefinitely"],"learning_resources":["https://www.evidentlyai.com/ml-in-production/data-drift"],"real_world_context":"Model monitoring for drift is a core MLOps practice to maintain production model quality."}
    ],
    "advanced": [
      {"question_id":"ml_adv_001","type":"scenario","question":"A model has high bias. Which approach is MOST likely to help?","options":["Increase regularisation","Add more training data indefinitely","Use a more complex model or add features","Remove outliers from training data"],"correct_answer":2,"explanation":"High bias means the model is too simple to capture the underlying patterns (underfitting). A more complex model architecture (more parameters, higher polynomial degree) or richer feature engineering directly addresses high bias.","difficulty_score":7,"time_seconds":90,"tags":["bias_variance","underfitting","model_complexity"],"prerequisites":["ml_int_001","ml_int_002"],"common_mistakes":["Adding more data to fix a bias problem (helps variance, not bias)"],"learning_resources":["https://developers.google.com/machine-learning/crash-course/"],"real_world_context":"Bias-variance diagnosis determines whether to collect more data or change the model architecture."},
      {"question_id":"ml_adv_002","type":"mcq","question":"What is the primary purpose of SHAP values in ML interpretability?","options":["Speed up model training","Explain each feature's contribution to a specific prediction using game theory","Replace cross-validation","Regularise model weights"],"correct_answer":1,"explanation":"SHAP (SHapley Additive exPlanations) uses game-theoretic Shapley values to fairly attribute each feature's contribution to a specific model prediction. Unlike global feature importance, SHAP provides local per-prediction explanations.","difficulty_score":8,"time_seconds":120,"tags":["SHAP","interpretability","explainability","XAI"],"prerequisites":["ml_adv_001"],"common_mistakes":["Confusing SHAP with global feature importance"],"learning_resources":["https://shap.readthedocs.io/en/latest/"],"real_world_context":"SHAP is required for regulatory compliance (GDPR right to explanation) in financial AI models."}
    ]
  }
}

dl_skill = {
  "skill_id": "deep_learning",
  "skill_name": "Deep Learning",
  "category": "machine_learning",
  "total_questions": 10,
  "levels": {
    "beginner": [
      {"question_id":"dl_beg_001","type":"mcq","question":"What is the role of an activation function in a neural network?","options":["Initialise weights","Introduce non-linearity, enabling the network to learn complex patterns","Normalise input data","Set the learning rate"],"correct_answer":1,"explanation":"Without activation functions all layers would collapse to a single linear transformation. Activation functions like ReLU, sigmoid, and tanh introduce non-linearity, allowing networks to approximate any function.","difficulty_score":2,"time_seconds":30,"tags":["activation_functions","neural_networks","non_linearity"],"prerequisites":[],"common_mistakes":["Thinking linear activation is sufficient for complex problems"],"learning_resources":["https://developers.google.com/machine-learning/crash-course/introduction-to-neural-networks/anatomy"],"real_world_context":"ReLU is the default activation for hidden layers in virtually all modern deep learning models."},
      {"question_id":"dl_beg_002","type":"true_false","question":"Batch normalisation helps speed up training by normalising layer inputs, reducing internal covariate shift.","correct_answer":True,"explanation":"BatchNorm normalises each mini-batch's activations to zero mean and unit variance, stabilising training. This allows higher learning rates and reduces sensitivity to weight initialisation, speeding up convergence significantly.","difficulty_score":3,"time_seconds":30,"tags":["batch_normalisation","training","convergence"],"prerequisites":["dl_beg_001"],"common_mistakes":["Thinking BatchNorm only regularises, not speeds up training"],"learning_resources":["https://arxiv.org/abs/1502.03167"],"real_world_context":"BatchNorm is used in ResNets, BERT, and essentially all production deep learning models."},
      {"question_id":"dl_beg_003","type":"mcq","question":"Which optimiser uses an adaptive learning rate per parameter and is widely used for training deep networks?","options":["SGD","Momentum","Adam","Adagrad"],"correct_answer":2,"explanation":"Adam (Adaptive Moment Estimation) maintains per-parameter learning rates using first and second moment estimates. It combines the benefits of AdaGrad and RMSProp, converging faster than plain SGD on most tasks.","difficulty_score":3,"time_seconds":45,"tags":["Adam","optimiser","training","deep_learning"],"prerequisites":["dl_beg_001"],"common_mistakes":["Using plain SGD without momentum for deep network training"],"learning_resources":["https://arxiv.org/abs/1412.6980"],"real_world_context":"Adam is the default optimiser for transformer models, CNNs, and most deep learning research."},
      {"question_id":"dl_beg_004","type":"true_false","question":"Dropout during training randomly deactivates neurons to reduce overfitting.","correct_answer":True,"explanation":"Dropout randomly sets a fraction of neurons to zero during each training forward pass. This prevents co-adaptation and forces the network to learn redundant representations, acting as an ensemble of many sub-networks.","difficulty_score":3,"time_seconds":30,"tags":["dropout","regularisation","overfitting"],"prerequisites":["dl_beg_001"],"common_mistakes":["Applying dropout during inference (should be disabled)","Using dropout rate=0.5 everywhere without tuning"],"learning_resources":["https://jmlr.org/papers/v15/srivastava14a.html"],"real_world_context":"Dropout is still used in transformer models like BERT in the attention and feed-forward layers."}
    ],
    "intermediate": [
      {"question_id":"dl_int_001","type":"mcq","question":"What is the vanishing gradient problem and which activation function helps address it?","options":["Gradients become NaN; solved by gradient clipping","Gradients shrink exponentially in deep networks; ReLU helps by having a gradient of 1 for positive inputs","Gradients grow too large; solved by sigmoid","Gradients are zero for all layers; solved by dropout"],"correct_answer":1,"explanation":"In deep networks, sigmoid/tanh gradients approach zero for large inputs, causing earlier layers to receive negligible updates. ReLU outputs gradient=1 for positive values, preventing shrinkage. Residual connections (ResNets) further address this.","difficulty_score":6,"time_seconds":75,"tags":["vanishing_gradient","ReLU","deep_learning","backpropagation"],"prerequisites":["dl_beg_001"],"common_mistakes":["Confusing vanishing and exploding gradients","Thinking ReLU completely solves the problem"],"learning_resources":["https://arxiv.org/abs/1502.01852"],"real_world_context":"Vanishing gradients were the primary blocker for training deep networks before ReLU and ResNets."},
      {"question_id":"dl_int_002","type":"scenario","question":"A CNN classifies images but performs poorly on slightly rotated versions. What is the BEST training strategy?","options":["Use a larger model","Apply data augmentation with rotations during training","Increase learning rate","Use a different loss function"],"correct_answer":1,"explanation":"Data augmentation introduces rotated, flipped, and cropped versions of training images, teaching the model to be invariant to these transformations. This is more effective than changing architecture or hyperparameters for geometric invariance.","difficulty_score":5,"time_seconds":75,"tags":["CNN","data_augmentation","invariance","computer_vision"],"prerequisites":["dl_beg_002"],"common_mistakes":["Adding more model capacity instead of fixing data distribution"],"learning_resources":["https://pytorch.org/vision/stable/transforms.html"],"real_world_context":"Data augmentation is mandatory in medical imaging where geometric invariance is critical."},
      {"question_id":"dl_int_003","type":"mcq","question":"What is the attention mechanism's key advantage in transformer models over RNNs?","options":["Attention uses less memory","Attention models dependencies regardless of distance in the sequence, in parallel","Attention has fewer parameters","Attention requires labelled data"],"correct_answer":1,"explanation":"Attention computes relationships between all token pairs simultaneously, capturing long-range dependencies that RNNs struggle with due to gradient issues. Parallel computation also makes transformers significantly faster to train on GPUs.","difficulty_score":6,"time_seconds":90,"tags":["attention","transformers","RNN","NLP"],"prerequisites":["dl_int_001"],"common_mistakes":["Thinking attention is just a weighted sum without understanding the query-key-value mechanism"],"learning_resources":["https://arxiv.org/abs/1706.03762"],"real_world_context":"The attention mechanism powers BERT, GPT, and all large language models."},
      {"question_id":"dl_int_004","type":"code_debugging","question":"A neural network loss is NaN after a few batches. What is the MOST likely cause?","options":["Batch size is too large","Learning rate is too high causing gradient explosion or log(0) in loss","Dropout rate is 0","Model has too many layers"],"correct_answer":1,"explanation":"NaN loss is almost always caused by: (1) learning rate too high leading to gradient explosion, or (2) log(0) in cross-entropy when the model predicts probability=0 for the true class. Use gradient clipping and label smoothing.","difficulty_score":6,"time_seconds":90,"tags":["NaN_loss","gradient_explosion","debugging","training"],"prerequisites":["dl_int_001"],"common_mistakes":["Reducing batch size instead of learning rate when NaN appears"],"learning_resources":["https://pytorch.org/docs/stable/nn.utils.html#torch.nn.utils.clip_grad_norm_"],"real_world_context":"NaN loss investigation is a common early-stage training debugging task in research and production."}
    ],
    "advanced": [
      {"question_id":"dl_adv_001","type":"scenario","question":"Fine-tuning a 7B parameter LLM on a single GPU with 24GB VRAM fails with OOM. What technique enables this?","options":["Use a smaller batch size only","Apply LoRA (Low-Rank Adaptation) to train only small adapter matrices","Switch to CPU training","Remove all dropout layers"],"correct_answer":1,"explanation":"LoRA freezes the pre-trained weights and trains small low-rank decomposition matrices (millions vs billions of parameters), reducing trainable parameters by 99%+. Combined with 4-bit quantisation this enables fine-tuning 7B models on consumer GPUs.","difficulty_score":9,"time_seconds":120,"tags":["LoRA","PEFT","fine_tuning","LLM","VRAM"],"prerequisites":["dl_int_003"],"common_mistakes":["Reducing batch size alone when the model params themselves don't fit","Not using quantisation alongside LoRA"],"learning_resources":["https://arxiv.org/abs/2106.09685"],"real_world_context":"LoRA is the standard technique for cost-effective LLM fine-tuning across academic and industry teams."},
      {"question_id":"dl_adv_002","type":"mcq","question":"What is knowledge distillation in deep learning?","options":["Transferring weights between identical models","Training a smaller student model to mimic a larger teacher model's output distribution","Compressing model weights to 8-bit integers","Pruning neurons with smallest activations"],"correct_answer":1,"explanation":"Knowledge distillation trains a compact student model to match the soft probability outputs of a large teacher model — not just the hard labels. The soft targets contain richer information about class relationships, yielding a better small model than training from scratch.","difficulty_score":8,"time_seconds":120,"tags":["knowledge_distillation","model_compression","student_teacher"],"prerequisites":["dl_adv_001"],"common_mistakes":["Confusing distillation with quantisation or pruning","Training student on hard labels only"],"learning_resources":["https://arxiv.org/abs/1503.02531"],"real_world_context":"DistilBERT and TinyBERT use distillation to compress BERT by 60% with minimal accuracy loss."}
    ]
  }
}

EXTRA_SKILLS = [docker_skill, k8s_skill, aws_skill, ml_skill, dl_skill]
