python_skill = {
  "skill_id": "python_programming",
  "skill_name": "Python Programming",
  "category": "backend_development",
  "total_questions": 20,
  "levels": {
    "beginner": [
      {"question_id":"py_beg_001","type":"mcq","question":"Which keyword is used to define a function in Python?","options":["function","def","func","define"],"correct_answer":1,"explanation":"'def' is the keyword used to define functions in Python. Unlike JavaScript which uses 'function', Python uses the shorter 'def'. Forgetting the colon after the parentheses is also a common syntax error.","difficulty_score":1,"time_seconds":30,"tags":["syntax","functions","basics"],"prerequisites":[],"common_mistakes":["Using 'function' like JavaScript","Forgetting the colon after parentheses"],"learning_resources":["https://docs.python.org/3/tutorial/controlflow.html#defining-functions"],"real_world_context":"Every Python program uses functions for code organisation."},
      {"question_id":"py_beg_002","type":"code_output","question":"What is the output?\n\n```python\nx = [1, 2, 3]\ny = x\ny.append(4)\nprint(len(x))\n```","options":["3","4","Error","None"],"correct_answer":1,"explanation":"Lists are assigned by reference; y and x point to the same object. Appending to y also modifies x, so len(x) is 4. Beginners often assume y = x creates a copy.","difficulty_score":3,"time_seconds":60,"tags":["lists","mutability","references"],"prerequisites":["py_beg_001"],"common_mistakes":["Assuming y is a copy of x","Not understanding references"],"learning_resources":["https://docs.python.org/3/library/stdtypes.html#list"],"real_world_context":"Mutable default arguments and shared state bugs originate from this behaviour."},
      {"question_id":"py_beg_003","type":"fill_in_blank","question":"Complete the list comprehension to square numbers 0-9:\n\nsquares = [_____ for x in range(10)]","correct_answer":"x**2","acceptable_answers":["x*x","x ** 2","pow(x,2)","pow(x, 2)"],"explanation":"List comprehensions use [expression for item in iterable]. x**2 raises x to the power 2. x*x is equivalent but less idiomatic. pow(x,2) also works but is verbose.","difficulty_score":4,"time_seconds":45,"tags":["list_comprehension","loops","syntax"],"prerequisites":["py_beg_001"],"common_mistakes":["Writing x^2 (XOR in Python)","Putting range inside brackets"],"learning_resources":["https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions"],"real_world_context":"List comprehensions are 30-40% faster than equivalent for-loops."},
      {"question_id":"py_beg_004","type":"true_false","question":"In Python, the expression 5 == \"5\" evaluates to True.","correct_answer":False,"explanation":"Python performs no automatic type coercion in equality comparisons; an int and a str are never equal. This differs from JavaScript where '5' == 5 is true due to type coercion.","difficulty_score":2,"time_seconds":30,"tags":["type_comparison","operators","data_types"],"prerequisites":["py_beg_001"],"common_mistakes":["Assuming Python coerces like JavaScript"],"learning_resources":["https://docs.python.org/3/reference/expressions.html#comparisons"],"real_world_context":"Silent type mismatches cause hard-to-find bugs when reading data from APIs."},
      {"question_id":"py_beg_005","type":"code_debugging","question":"Identify the error:\n\n```python\ndef greet()\n    print('Hello World')\ngreet()\n```","options":["Missing colon after function definition","Missing return statement","Wrong indentation","print should be Print"],"correct_answer":0,"explanation":"Python function definitions must end with a colon ':'. The correct line is 'def greet():'. Missing the colon raises a SyntaxError immediately.","difficulty_score":2,"time_seconds":45,"tags":["syntax","debugging","functions"],"prerequisites":["py_beg_001"],"common_mistakes":["Forgetting the colon","Blaming indentation first"],"learning_resources":["https://docs.python.org/3/reference/compound_stmts.html#function-definitions"],"real_world_context":"SyntaxError from missing colons is among the most frequent beginner Python errors."},
      {"question_id":"py_beg_006","type":"mcq","question":"Which built-in function returns the number of items in a list?","options":["size()","count()","len()","length()"],"correct_answer":2,"explanation":"len() is the built-in function that returns the number of items in any sequence or collection. size() and length() do not exist as built-ins; count() counts occurrences of a specific value.","difficulty_score":1,"time_seconds":30,"tags":["built_ins","lists","basics"],"prerequisites":[],"common_mistakes":["Using .size() like Java","Using .length like JavaScript"],"learning_resources":["https://docs.python.org/3/library/functions.html#len"],"real_world_context":"len() works on strings, lists, tuples, dicts, and sets."},
      {"question_id":"py_beg_007","type":"true_false","question":"Python tuples are mutable, meaning their elements can be changed after creation.","correct_answer":False,"explanation":"Tuples are immutable; once created their elements cannot be changed. Lists are the mutable counterpart. Attempting tuple[0]=1 raises a TypeError.","difficulty_score":2,"time_seconds":30,"tags":["tuples","mutability","data_types"],"prerequisites":["py_beg_001"],"common_mistakes":["Confusing tuples with lists","Thinking parentheses make something mutable"],"learning_resources":["https://docs.python.org/3/library/stdtypes.html#tuples"],"real_world_context":"Tuples are used as hashable dict keys and in database row results."},
      {"question_id":"py_beg_008","type":"code_output","question":"What does this print?\n\n```python\nfor i in range(2, 10, 3):\n    print(i, end=' ')\n```","options":["2 5 8","2 4 6 8","3 6 9","2 3 4 5 6 7 8 9"],"correct_answer":0,"explanation":"range(start, stop, step) generates 2, 5, 8. The step is 3, stop is exclusive at 10, so 11 would exceed. Many confuse stop as inclusive.","difficulty_score":3,"time_seconds":45,"tags":["range","loops","iteration"],"prerequisites":["py_beg_001"],"common_mistakes":["Thinking stop is inclusive","Ignoring the step parameter"],"learning_resources":["https://docs.python.org/3/library/stdtypes.html#range"],"real_world_context":"range() with step is useful for batch processing every Nth item."}
    ],
    "intermediate": [
      {"question_id":"py_int_001","type":"mcq","question":"What is the average time complexity of accessing an element in a Python dictionary by key?","options":["O(1)","O(log n)","O(n)","O(n²)"],"correct_answer":0,"explanation":"Python dicts are hash tables providing O(1) average lookup. Worst-case is O(n) due to hash collisions but this is extremely rare with a good hash function.","difficulty_score":5,"time_seconds":45,"tags":["data_structures","complexity","dictionaries"],"prerequisites":["py_beg_006"],"common_mistakes":["Thinking dicts scan linearly"],"learning_resources":["https://wiki.python.org/moin/TimeComplexity"],"real_world_context":"Choosing dict over list for lookups is a common performance optimisation."},
      {"question_id":"py_int_002","type":"scenario","question":"You need to process a 10 GB CSV on a 4 GB RAM machine. Which is most memory-efficient?","options":["pd.read_csv() entire file","pd.read_csv() with chunksize","Load into SQLite first","Convert to JSON then process"],"correct_answer":1,"explanation":"chunksize reads the file in batches, keeping RAM usage constant regardless of file size. Loading the whole file would exceed available RAM and crash the process.","difficulty_score":6,"time_seconds":90,"tags":["file_processing","memory_management","pandas"],"prerequisites":["py_int_001"],"common_mistakes":["Loading whole file then filtering","Using JSON which is larger than CSV"],"learning_resources":["https://pandas.pydata.org/docs/user_guide/io.html#io-chunking"],"real_world_context":"Standard pattern in data engineering pipelines with large datasets."},
      {"question_id":"py_int_003","type":"code_output","question":"What is the output?\n\n```python\ndef func(a, b=[]):\n    b.append(a)\n    return b\nprint(func(1))\nprint(func(2))\n```","options":["[1] then [2]","[1] then [1,2]","Error","[1] then [2,1]"],"correct_answer":1,"explanation":"Default mutable arguments are created once at function definition time, not on each call. The list b persists across calls, so the second call appends to the existing [1].","difficulty_score":6,"time_seconds":90,"tags":["mutable_defaults","functions","gotchas"],"prerequisites":["py_beg_001"],"common_mistakes":["Thinking defaults reset on each call"],"learning_resources":["https://docs.python.org/3/faq/programming.html#why-are-default-values-shared-between-objects"],"real_world_context":"This is a notorious Python gotcha that causes subtle state bugs in production."},
      {"question_id":"py_int_004","type":"mcq","question":"Which decorator caches the return value of a function for repeated inputs?","options":["@staticmethod","@functools.lru_cache","@classmethod","@property"],"correct_answer":1,"explanation":"functools.lru_cache memoises function results so repeated calls with the same arguments return the cached value instantly. The others are unrelated to caching.","difficulty_score":5,"time_seconds":60,"tags":["decorators","caching","functools"],"prerequisites":["py_beg_001"],"common_mistakes":["Using @staticmethod which has no caching","Manually writing a dict cache instead"],"learning_resources":["https://docs.python.org/3/library/functools.html#functools.lru_cache"],"real_world_context":"lru_cache dramatically speeds up recursive algorithms like Fibonacci."},
      {"question_id":"py_int_005","type":"code_debugging","question":"Why does this generator raise StopIteration without yielding all values?\n\n```python\ndef gen():\n    yield 1\n    return\n    yield 2\n```","options":["return exits the generator early","yield 2 is unreachable code","return raises StopIteration","Both A and C"],"correct_answer":3,"explanation":"In a generator, a bare return statement raises StopIteration, ending the generator. Code after return is unreachable, so yield 2 is never executed. Both A and C are correct.","difficulty_score":6,"time_seconds":75,"tags":["generators","iteration","control_flow"],"prerequisites":["py_int_002"],"common_mistakes":["Thinking return value is yielded","Not knowing return ends a generator"],"learning_resources":["https://docs.python.org/3/reference/expressions.html#yield-expressions"],"real_world_context":"Generators are the backbone of memory-efficient streaming data pipelines."},
      {"question_id":"py_int_006","type":"mcq","question":"What does the __slots__ class attribute do?","options":["Prevents subclassing","Restricts instance attributes saving memory","Makes class abstract","Enables multiple inheritance"],"correct_answer":1,"explanation":"__slots__ replaces the per-instance __dict__ with a fixed set of slots, dramatically reducing memory usage for classes with many instances. It also prevents adding arbitrary attributes.","difficulty_score":6,"time_seconds":60,"tags":["oop","memory","optimization"],"prerequisites":["py_int_001"],"common_mistakes":["Thinking it prevents subclassing","Thinking it is related to threading"],"learning_resources":["https://docs.python.org/3/reference/datamodel.html#slots"],"real_world_context":"Used in high-performance systems storing millions of lightweight objects."},
      {"question_id":"py_int_007","type":"code_output","question":"What is printed?\n\n```python\nclass A:\n    val = 0\na = A()\nA.val = 5\nprint(a.val)\n```","options":["0","5","AttributeError","None"],"correct_answer":1,"explanation":"a.val looks up the instance dict first; since no instance attribute is set, it falls back to the class attribute A.val which is 5. Changing the class attribute affects all instances without their own override.","difficulty_score":5,"time_seconds":60,"tags":["oop","class_attributes","python_model"],"prerequisites":["py_beg_001"],"common_mistakes":["Thinking instance is isolated from class changes"],"learning_resources":["https://docs.python.org/3/tutorial/classes.html"],"real_world_context":"Shared class attributes can cause unexpected shared state in ORMs."},
      {"question_id":"py_int_008","type":"scenario","question":"You need to run multiple I/O-bound HTTP requests concurrently. What is the best Python approach?","options":["threading.Thread for each request","asyncio with aiohttp","multiprocessing.Pool","subprocess.run in parallel"],"correct_answer":1,"explanation":"For I/O-bound tasks, asyncio with aiohttp provides concurrency without OS thread overhead. threading works but has GIL contention; multiprocessing adds serialisation overhead for purely I/O tasks.","difficulty_score":6,"time_seconds":90,"tags":["async","concurrency","io_bound"],"prerequisites":["py_int_003"],"common_mistakes":["Using multiprocessing for I/O-bound tasks","Thinking GIL blocks I/O threads"],"learning_resources":["https://docs.aiohttp.org/en/stable/"],"real_world_context":"Async HTTP is the standard for microservice fans-out and web scrapers."}
    ],
    "advanced": [
      {"question_id":"py_adv_001","type":"code_analysis","question":"What design pattern is implemented here?\n\n```python\nclass DB:\n    _instance = None\n    def __new__(cls):\n        if cls._instance is None:\n            cls._instance = super().__new__(cls)\n        return cls._instance\n```","options":["Factory","Singleton","Observer","Strategy"],"correct_answer":1,"explanation":"Overriding __new__ to return a shared _instance ensures only one object ever exists — the Singleton pattern. The Factory pattern creates new objects; Observer and Strategy are behavioural patterns.","difficulty_score":8,"time_seconds":120,"tags":["design_patterns","oop","singleton"],"prerequisites":["py_int_007"],"common_mistakes":["Confusing with Factory","Thinking __init__ handles singleton logic"],"learning_resources":["https://refactoring.guru/design-patterns/singleton/python/example"],"real_world_context":"Database connection pools and config managers use Singleton to avoid duplicate connections."},
      {"question_id":"py_adv_002","type":"scenario","question":"A Python web service leaks memory over 24 h but memory_profiler shows no Python heap growth. What is the most likely cause?","options":["Reference cycles in pure Python","C extension or native library not releasing memory","Too many open file descriptors","Database connection pool leak"],"correct_answer":1,"explanation":"If the Python heap appears stable, the leak is outside Python's allocator — typically a C extension (e.g., NumPy, lxml) that does not release native memory. Reference cycles are caught by Python's cyclic GC.","difficulty_score":9,"time_seconds":120,"tags":["memory_leaks","debugging","c_extensions"],"prerequisites":["py_adv_001"],"common_mistakes":["Blaming Python GC first","Restarting service instead of diagnosing"],"learning_resources":["https://docs.python.org/3/c-api/memory.html"],"real_world_context":"Production memory leaks in ML services are often numpy/C binding issues."},
      {"question_id":"py_adv_003","type":"mcq","question":"What is the output of `type(lambda: None).__name__`?","options":["'function'","'lambda'","'NoneType'","'method'"],"correct_answer":0,"explanation":"Lambda expressions produce regular function objects; their type is 'function', same as def-defined functions. There is no special 'lambda' type in Python's type system.","difficulty_score":7,"time_seconds":90,"tags":["lambdas","type_system","introspection"],"prerequisites":["py_int_004"],"common_mistakes":["Expecting 'lambda' as the type name"],"learning_resources":["https://docs.python.org/3/reference/expressions.html#lambda"],"real_world_context":"Understanding function types matters when writing decorators and reflection utilities."},
      {"question_id":"py_adv_004","type":"code_analysis","question":"In CPython, what prevents two threads from executing Python bytecode simultaneously?","options":["asyncio event loop","Global Interpreter Lock (GIL)","threading.Semaphore","The OS scheduler"],"correct_answer":1,"explanation":"The GIL is a mutex in CPython that allows only one thread to execute bytecode at a time. This simplifies memory management but limits CPU-bound parallelism; I/O-bound threads can release the GIL while waiting.","difficulty_score":8,"time_seconds":120,"tags":["GIL","threading","CPython","concurrency"],"prerequisites":["py_int_008"],"common_mistakes":["Thinking asyncio removes the GIL","Confusing GIL with OS scheduling"],"learning_resources":["https://docs.python.org/3/glossary.html#term-global-interpreter-lock"],"real_world_context":"The GIL is why CPU-bound Python code uses multiprocessing, not threading."}
    ]
  }
}

js_skill = {
  "skill_id": "javascript_nodejs",
  "skill_name": "JavaScript / Node.js",
  "category": "backend_development",
  "total_questions": 15,
  "levels": {
    "beginner": [
      {"question_id":"js_beg_001","type":"mcq","question":"Which keyword declares a block-scoped variable in modern JavaScript?","options":["var","let","function","declare"],"correct_answer":1,"explanation":"'let' declares a block-scoped variable in ES6+. 'var' is function-scoped and hoisted, which causes subtle bugs. 'function' and 'declare' are not variable declarations.","difficulty_score":2,"time_seconds":30,"tags":["variables","scope","es6"],"prerequisites":[],"common_mistakes":["Using var in modern code","Confusing let with const"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let"],"real_world_context":"let and const replaced var in all modern JS codebases."},
      {"question_id":"js_beg_002","type":"true_false","question":"In JavaScript, '==' performs strict equality checking (type + value).","correct_answer":False,"explanation":"'==' performs loose equality with type coercion, so '5' == 5 is true. '===' performs strict equality checking both type and value. Always prefer '===' in production code.","difficulty_score":2,"time_seconds":30,"tags":["operators","equality","types"],"prerequisites":["js_beg_001"],"common_mistakes":["Using == and expecting strict comparison"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness"],"real_world_context":"Accidental == usage is a common source of logic bugs in JS applications."},
      {"question_id":"js_beg_003","type":"code_output","question":"What is logged?\n\n```javascript\nconsole.log(typeof null);\n```","options":["'null'","'object'","'undefined'","TypeError"],"correct_answer":1,"explanation":"typeof null returns 'object' — a well-known JavaScript bug that was never fixed for backwards compatibility. null is not actually an object; always use === null to check for null.","difficulty_score":3,"time_seconds":30,"tags":["typeof","null","quirks"],"prerequisites":["js_beg_001"],"common_mistakes":["Expecting 'null' as the type"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof"],"real_world_context":"typeof checks for null are unreliable; always use strict equality."},
      {"question_id":"js_beg_004","type":"mcq","question":"Which method adds one or more elements to the END of an array?","options":["push()","pop()","shift()","unshift()"],"correct_answer":0,"explanation":"push() appends elements to the end of an array. pop() removes the last element. shift() removes the first. unshift() adds to the beginning.","difficulty_score":1,"time_seconds":30,"tags":["arrays","methods","basics"],"prerequisites":[],"common_mistakes":["Confusing push with unshift"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push"],"real_world_context":"push/pop form a stack; shift/unshift form a queue in array-based data structures."},
      {"question_id":"js_beg_005","type":"code_output","question":"What is the output?\n\n```javascript\nconst obj = {a: 1};\nconst {a, b = 10} = obj;\nconsole.log(b);\n```","options":["undefined","10","1","ReferenceError"],"correct_answer":1,"explanation":"Destructuring allows default values. Since 'b' does not exist in obj, the default 10 is used. If 'b' existed with value undefined, the default would also apply.","difficulty_score":3,"time_seconds":45,"tags":["destructuring","defaults","es6"],"prerequisites":["js_beg_001"],"common_mistakes":["Expecting undefined when key is missing"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment"],"real_world_context":"Default destructuring values are common in React props patterns."},
      {"question_id":"js_beg_006","type":"true_false","question":"Arrow functions have their own 'this' binding.","correct_answer":False,"explanation":"Arrow functions do not have their own 'this'; they inherit 'this' from the enclosing lexical scope. Regular functions create their own 'this' which depends on the call context.","difficulty_score":3,"time_seconds":30,"tags":["arrow_functions","this","scope"],"prerequisites":["js_beg_001"],"common_mistakes":["Using arrow functions as object methods expecting this = object"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions"],"real_world_context":"Arrow functions are preferred for callbacks to avoid losing 'this' context."}
    ],
    "intermediate": [
      {"question_id":"js_int_001","type":"mcq","question":"What does the Event Loop do when the call stack is empty?","options":["Terminates the program","Processes the next task from the callback queue","Runs the garbage collector","Restarts the main module"],"correct_answer":1,"explanation":"The event loop continuously checks if the call stack is empty, then dequeues the next callback from the task queue to execute. This is the basis of Node.js non-blocking I/O.","difficulty_score":5,"time_seconds":60,"tags":["event_loop","async","nodejs"],"prerequisites":["js_beg_004"],"common_mistakes":["Thinking Node.js is truly multi-threaded"],"learning_resources":["https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick"],"real_world_context":"Understanding the event loop is critical for debugging async behaviour in Node."},
      {"question_id":"js_int_002","type":"code_output","question":"What is printed?\n\n```javascript\nasync function foo() { return 42; }\nconst result = foo();\nconsole.log(result);\n```","options":["42","Promise { 42 }","undefined","Promise { <pending> }"],"correct_answer":3,"explanation":"async functions always return a Promise. Without await, the Promise is pending when console.log runs. Use 'await foo()' or '.then()' to access the resolved value 42.","difficulty_score":5,"time_seconds":60,"tags":["async","promises","async_await"],"prerequisites":["js_int_001"],"common_mistakes":["Expecting the raw return value without await"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function"],"real_world_context":"Forgetting await is one of the most common async bugs in production JS."},
      {"question_id":"js_int_003","type":"scenario","question":"A Node.js API reads from a DB and returns JSON. Response times spike under load. What should you investigate first?","options":["CPU usage of Node process","Number of unclosed DB connections","RAM usage on the server","SSL certificate validity"],"correct_answer":1,"explanation":"Unclosed database connections exhaust the connection pool, causing new requests to queue and response times to spike. CPU is rarely the bottleneck in I/O-bound Node APIs.","difficulty_score":6,"time_seconds":90,"tags":["nodejs","performance","database","connection_pool"],"prerequisites":["js_int_001"],"common_mistakes":["Scaling horizontally before fixing connection leaks","Blaming CPU for I/O-bound slowness"],"learning_resources":["https://nodejs.org/api/https.html"],"real_world_context":"Connection pool exhaustion is the #1 Node.js production performance issue."},
      {"question_id":"js_int_004","type":"code_debugging","question":"Why does this cause unexpected behaviour?\n\n```javascript\nconst cache = {};\nfunction get(key) {\n  if (!cache[key]) return fetch(key);\n  return cache[key];\n}\n```","options":["fetch is not defined","Falsy cached values (0, false, '') bypass cache","cache is not initialised","return is missing await"],"correct_answer":1,"explanation":"!cache[key] is true for falsy values like 0, '', or false, so valid cached results are ignored and fetch is called again. Use hasOwnProperty or key in cache instead.","difficulty_score":6,"time_seconds":75,"tags":["caching","falsy_values","bugs"],"prerequisites":["js_int_002"],"common_mistakes":["Not accounting for falsy legitimate values","Using ! for existence checks"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Glossary/Falsy"],"real_world_context":"Falsy cache bugs silently break caching layers in production services."},
      {"question_id":"js_int_005","type":"mcq","question":"Which Node.js module handles file system operations?","options":["http","path","fs","os"],"correct_answer":2,"explanation":"The 'fs' module provides file system operations like reading, writing, and deleting files. 'http' handles web requests, 'path' handles path strings, 'os' provides OS information.","difficulty_score":4,"time_seconds":30,"tags":["nodejs","modules","fs"],"prerequisites":["js_beg_001"],"common_mistakes":["Confusing path with fs for file operations"],"learning_resources":["https://nodejs.org/api/fs.html"],"real_world_context":"fs.promises is used in every Node backend that reads config files or writes logs."},
      {"question_id":"js_int_006","type":"true_false","question":"Promise.all() resolves when ANY ONE of its promises resolves.","correct_answer":False,"explanation":"Promise.all() resolves only when ALL promises resolve; it rejects immediately if any promise rejects. Promise.race() resolves/rejects when the first promise settling does.","difficulty_score":5,"time_seconds":45,"tags":["promises","Promise.all","concurrency"],"prerequisites":["js_int_002"],"common_mistakes":["Confusing Promise.all with Promise.race"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all"],"real_world_context":"Promise.all is used to fan-out multiple API calls in parallel and wait for all results."}
    ],
    "advanced": [
      {"question_id":"js_adv_001","type":"code_analysis","question":"What is the output?\n\n```javascript\nlet x = 1;\nfunction outer() {\n  let x = 2;\n  return function inner() { return x; };\n}\nconsole.log(outer()());\n```","options":["1","2","undefined","ReferenceError"],"correct_answer":1,"explanation":"inner forms a closure over the outer function's scope and captures x=2. When outer() returns inner and inner() is called, it accesses the closed-over x=2, not the global x=1.","difficulty_score":7,"time_seconds":90,"tags":["closures","scope","advanced_functions"],"prerequisites":["js_int_003"],"common_mistakes":["Expecting global x=1","Thinking the inner function sees global scope only"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures"],"real_world_context":"Closures power module patterns, event handlers, and React hooks."},
      {"question_id":"js_adv_002","type":"scenario","question":"A Node.js service must handle 10,000 concurrent WebSocket connections. What is the primary architectural concern?","options":["Memory per connection object","CPU for JSON parsing","Disk I/O for logs","SSL handshake time"],"correct_answer":0,"explanation":"Each WebSocket connection holds a socket object in memory. 10,000 connections can consume gigabytes of RAM if not carefully managed. CPU and disk are secondary concerns for I/O-bound connections.","difficulty_score":8,"time_seconds":120,"tags":["websockets","scalability","memory"],"prerequisites":["js_adv_001"],"common_mistakes":["Focusing on CPU before RAM","Forgetting connection state memory"],"learning_resources":["https://www.npmjs.com/package/ws"],"real_world_context":"Real-time chat and gaming backends face this scaling challenge daily."},
      {"question_id":"js_adv_003","type":"mcq","question":"What memory issue can arise from storing DOM references in a Map vs a WeakMap?","options":["Map causes prototype pollution","Map prevents garbage collection of removed DOM nodes","WeakMap throws on non-objects","No difference"],"correct_answer":1,"explanation":"A strong Map reference keeps DOM nodes alive in memory even after removal from the DOM, causing memory leaks. WeakMap holds weak references so removed nodes can be garbage-collected.","difficulty_score":8,"time_seconds":120,"tags":["WeakMap","memory_leaks","garbage_collection"],"prerequisites":["js_adv_001"],"common_mistakes":["Thinking Map and WeakMap differ only in API","Not considering GC implications"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap"],"real_world_context":"WeakMap is the correct choice for DOM metadata caches in long-running SPAs."}
    ]
  }
}

sql_skill = {
  "skill_id": "sql",
  "skill_name": "SQL",
  "category": "backend_development",
  "total_questions": 15,
  "levels": {
    "beginner": [
      {"question_id":"sql_beg_001","type":"mcq","question":"Which SQL clause filters rows AFTER aggregation?","options":["WHERE","HAVING","GROUP BY","ORDER BY"],"correct_answer":1,"explanation":"HAVING filters groups after GROUP BY aggregation. WHERE filters individual rows before aggregation. Using WHERE on aggregate functions like COUNT() causes a syntax error.","difficulty_score":3,"time_seconds":45,"tags":["aggregation","filtering","clauses"],"prerequisites":[],"common_mistakes":["Using WHERE with aggregate functions","Forgetting HAVING requires GROUP BY"],"learning_resources":["https://www.w3schools.com/sql/sql_having.asp"],"real_world_context":"HAVING is used to find customers with more than 5 orders, for example."},
      {"question_id":"sql_beg_002","type":"true_false","question":"A PRIMARY KEY constraint automatically creates a UNIQUE index on the column.","correct_answer":True,"explanation":"PRIMARY KEY enforces both NOT NULL and UNIQUE constraints, and most databases automatically create a unique index to enforce uniqueness efficiently.","difficulty_score":2,"time_seconds":30,"tags":["constraints","indexing","primary_key"],"prerequisites":["sql_beg_001"],"common_mistakes":["Thinking PRIMARY KEY and UNIQUE are identical","Not knowing an index is auto-created"],"learning_resources":["https://www.postgresql.org/docs/current/ddl-constraints.html"],"real_world_context":"Understanding implicit indexes helps avoid redundant manual index creation."},
      {"question_id":"sql_beg_003","type":"code_output","question":"How many rows does this return?\n\nTable users has 5 rows. 2 have NULL email.\n\n```sql\nSELECT COUNT(email) FROM users;\n```","options":["5","3","2","NULL"],"correct_answer":1,"explanation":"COUNT(column) counts non-NULL values only. Since 2 emails are NULL, only 3 are counted. COUNT(*) would return 5 including NULLs.","difficulty_score":3,"time_seconds":45,"tags":["COUNT","NULL","aggregation"],"prerequisites":["sql_beg_001"],"common_mistakes":["Using COUNT(column) expecting it to count all rows"],"learning_resources":["https://www.postgresql.org/docs/current/functions-aggregate.html"],"real_world_context":"NULL handling in COUNT is a common interview trap and production bug source."},
      {"question_id":"sql_beg_004","type":"mcq","question":"Which JOIN returns all rows from the left table even if there is no match in the right table?","options":["INNER JOIN","LEFT JOIN","CROSS JOIN","RIGHT JOIN"],"correct_answer":1,"explanation":"LEFT JOIN returns all rows from the left table with NULLs for unmatched right table columns. INNER JOIN only returns matching rows. CROSS JOIN returns the cartesian product.","difficulty_score":3,"time_seconds":45,"tags":["joins","left_join","basics"],"prerequisites":["sql_beg_001"],"common_mistakes":["Confusing LEFT and INNER JOIN","Forgetting unmatched rows get NULL values"],"learning_resources":["https://www.postgresql.org/docs/current/queries-table-expressions.html"],"real_world_context":"LEFT JOIN is used to find customers who have never placed an order."},
      {"question_id":"sql_beg_005","type":"fill_in_blank","question":"Complete the query to find all users whose name starts with 'A':\n\n```sql\nSELECT * FROM users WHERE name _____ 'A%';\n```","correct_answer":"LIKE","acceptable_answers":["like","LIKE"],"explanation":"LIKE with wildcard % matches any sequence of characters. 'A%' matches strings starting with 'A'. ILIKE is the case-insensitive variant in PostgreSQL.","difficulty_score":2,"time_seconds":30,"tags":["LIKE","wildcards","filtering"],"prerequisites":[],"common_mistakes":["Using = instead of LIKE for pattern matching","Forgetting % means any characters"],"learning_resources":["https://www.w3schools.com/sql/sql_like.asp"],"real_world_context":"LIKE is used in search features but full-text indexes (tsvector) are more efficient at scale."},
      {"question_id":"sql_beg_006","type":"mcq","question":"What does DISTINCT do in a SELECT statement?","options":["Sorts results alphabetically","Removes duplicate rows from results","Filters NULL values","Limits rows returned"],"correct_answer":1,"explanation":"DISTINCT eliminates duplicate rows from the query result set. It operates on the entire selected row, not just one column, unless combined with specific functions.","difficulty_score":2,"time_seconds":30,"tags":["DISTINCT","deduplication","select"],"prerequisites":[],"common_mistakes":["Thinking DISTINCT sorts the results","Using DISTINCT on one column affecting all columns"],"learning_resources":["https://www.postgresql.org/docs/current/sql-select.html"],"real_world_context":"DISTINCT is often overused; GROUP BY is frequently more efficient for complex deduplication."}
    ],
    "intermediate": [
      {"question_id":"sql_int_001","type":"mcq","question":"What is the difference between TRUNCATE and DELETE without WHERE?","options":["No difference","TRUNCATE is logged, DELETE is not","TRUNCATE is faster and not fully logged, DELETE is row-by-row","DELETE is faster than TRUNCATE"],"correct_answer":2,"explanation":"TRUNCATE deallocates pages and is minimally logged, making it much faster for large tables. DELETE removes rows one-by-one and is fully logged, allowing rollback per row but at high cost.","difficulty_score":5,"time_seconds":60,"tags":["DDL","DML","performance"],"prerequisites":["sql_beg_001"],"common_mistakes":["Thinking they are equivalent","Forgetting TRUNCATE cannot be used with WHERE"],"learning_resources":["https://www.postgresql.org/docs/current/sql-truncate.html"],"real_world_context":"TRUNCATE is the correct way to reset staging tables in ETL pipelines."},
      {"question_id":"sql_int_002","type":"scenario","question":"A query joining 3 large tables is slow. EXPLAIN shows a sequential scan on orders(1M rows). What helps most?","options":["Add more RAM","Create index on the JOIN column","Use SELECT *","Split query into subqueries"],"correct_answer":1,"explanation":"A sequential scan on 1M rows on a join column indicates a missing index. Adding a B-tree index on the join column allows the query planner to use an index scan, drastically reducing I/O.","difficulty_score":6,"time_seconds":90,"tags":["performance","indexing","query_optimization","EXPLAIN"],"prerequisites":["sql_beg_002"],"common_mistakes":["Adding hardware before analysing the query plan"],"learning_resources":["https://www.postgresql.org/docs/current/sql-explain.html"],"real_world_context":"Query optimisation with EXPLAIN ANALYZE is a core DBA and backend skill."},
      {"question_id":"sql_int_003","type":"code_output","question":"What does this return?\n\n```sql\nSELECT 1 WHERE NULL = NULL;\n```","options":["1","0 rows","NULL","Error"],"correct_answer":1,"explanation":"NULL = NULL evaluates to UNKNOWN (not TRUE) in SQL's three-valued logic. The WHERE clause only passes rows where the condition is TRUE, so no rows are returned.","difficulty_score":6,"time_seconds":60,"tags":["NULL","three_valued_logic","SQL_semantics"],"prerequisites":["sql_int_001"],"common_mistakes":["Expecting NULL = NULL to be TRUE"],"learning_resources":["https://www.postgresql.org/docs/current/functions-comparison.html"],"real_world_context":"NULL comparisons are a source of silent bugs in reporting queries."},
      {"question_id":"sql_int_004","type":"mcq","question":"Which window function returns the rank of a row with NO gaps for ties?","options":["RANK()","ROW_NUMBER()","DENSE_RANK()","NTILE()"],"correct_answer":2,"explanation":"DENSE_RANK() assigns consecutive ranks without gaps: tied rows get the same rank and the next rank is one higher. RANK() leaves gaps after tied rows. ROW_NUMBER() gives unique sequential numbers ignoring ties.","difficulty_score":5,"time_seconds":60,"tags":["window_functions","ranking","analytics"],"prerequisites":["sql_int_001"],"common_mistakes":["Confusing RANK and DENSE_RANK gap behaviour"],"learning_resources":["https://www.postgresql.org/docs/current/functions-window.html"],"real_world_context":"DENSE_RANK() is used in leaderboards and top-N reporting queries."},
      {"question_id":"sql_int_005","type":"code_debugging","question":"This query returns incorrect totals. Why?\n\n```sql\nSELECT dept, SUM(salary)\nFROM employees\nGROUP BY department;\n```","options":["SUM cannot be used with GROUP BY","Column alias mismatch: dept vs department","Salary column must be quoted","Missing ORDER BY"],"correct_answer":1,"explanation":"The SELECT clause uses 'dept' but GROUP BY uses 'department'. If these are different column names, the query will error or group incorrectly. Column names must be consistent.","difficulty_score":5,"time_seconds":60,"tags":["GROUP_BY","column_names","debugging"],"prerequisites":["sql_beg_001"],"common_mistakes":["Using aliases inconsistently across clauses"],"learning_resources":["https://www.postgresql.org/docs/current/sql-select.html#SQL-GROUPBY"],"real_world_context":"Column name mismatches in complex reports cause silent wrong-total bugs."},
      {"question_id":"sql_int_006","type":"mcq","question":"What does a covering index provide?","options":["Prevents duplicate rows","Allows query to be answered from the index alone without table lookup","Automatically updates statistics","Encrypts indexed columns"],"correct_answer":1,"explanation":"A covering index includes all columns needed by a query, allowing the DB to return results directly from the index without accessing the main table (heap), eliminating costly random I/O.","difficulty_score":6,"time_seconds":75,"tags":["indexing","covering_index","performance"],"prerequisites":["sql_int_002"],"common_mistakes":["Thinking any index is a covering index","Not including SELECT columns in the index"],"learning_resources":["https://use-the-index-luke.com/sql/clustering/index-only-scan-covering-index"],"real_world_context":"Covering indexes can reduce query latency by 10x on hot read paths."}
    ],
    "advanced": [
      {"question_id":"sql_adv_001","type":"scenario","question":"A query on a 10M row table is slow. EXPLAIN shows 'Using filesort'. Which optimisation is most effective?","options":["Add more RAM","Create index on ORDER BY column","Partition the table","Use LIMIT to reduce rows"],"correct_answer":1,"explanation":"'Using filesort' means the DB cannot use an index for sorting. Creating an index on the ORDER BY column allows index-based ordering, eliminating the filesort and dramatically improving performance.","difficulty_score":8,"time_seconds":120,"tags":["performance","indexing","filesort","EXPLAIN"],"prerequisites":["sql_int_002","sql_int_006"],"common_mistakes":["Adding hardware before optimising queries","Over-partitioning without need"],"learning_resources":["https://dev.mysql.com/doc/refman/8.0/en/order-by-optimization.html"],"real_world_context":"Critical for production databases with large sorted result sets."},
      {"question_id":"sql_adv_002","type":"code_analysis","question":"What isolation level prevents phantom reads?","options":["READ UNCOMMITTED","READ COMMITTED","REPEATABLE READ","SERIALIZABLE"],"correct_answer":3,"explanation":"SERIALIZABLE is the only standard isolation level that prevents phantom reads (new rows inserted by other transactions appearing in repeated queries). REPEATABLE READ prevents non-repeatable reads but not phantoms in most databases.","difficulty_score":9,"time_seconds":120,"tags":["transactions","isolation_levels","ACID"],"prerequisites":["sql_adv_001"],"common_mistakes":["Thinking REPEATABLE READ prevents phantom reads (PostgreSQL is MVCC exception)"],"learning_resources":["https://www.postgresql.org/docs/current/transaction-iso.html"],"real_world_context":"Choosing the right isolation level is critical for financial and inventory systems."},
      {"question_id":"sql_adv_003","type":"mcq","question":"In PostgreSQL, what does VACUUM do?","options":["Deletes all rows","Reclaims storage from dead tuples","Rebuilds all indexes","Drops temporary tables"],"correct_answer":1,"explanation":"PostgreSQL's MVCC model marks deleted/updated rows as dead tuples without immediately freeing space. VACUUM reclaims this storage and updates visibility maps. Without it, tables bloat over time.","difficulty_score":8,"time_seconds":120,"tags":["PostgreSQL","MVCC","maintenance","VACUUM"],"prerequisites":["sql_adv_002"],"common_mistakes":["Thinking DELETE immediately frees disk space in PostgreSQL"],"learning_resources":["https://www.postgresql.org/docs/current/sql-vacuum.html"],"real_world_context":"Autovacuum tuning is a critical PostgreSQL production operations task."}
    ]
  }
}

skills = [python_skill, js_skill, sql_skill]
