rest_skill = {
  "skill_id": "rest_apis",
  "skill_name": "REST APIs",
  "category": "backend_development",
  "total_questions": 10,
  "levels": {
    "beginner": [
      {"question_id":"rest_beg_001","type":"mcq","question":"Which HTTP method is used to retrieve data from a server?","options":["POST","PUT","GET","DELETE"],"correct_answer":2,"explanation":"GET is the standard HTTP method for retrieving resources without side effects (read-only operations). POST creates, PUT replaces/updates, and DELETE removes.","difficulty_score":1,"time_seconds":30,"tags":["HTTP","methods","GET"],"prerequisites":[],"common_mistakes":["Confusing GET with POST"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods"],"real_world_context":"Every API consumer uses GET to fetch data for display."},
      {"question_id":"rest_beg_002","type":"true_false","question":"A POST request is idempotent.","correct_answer":False,"explanation":"POST is not idempotent. Sending the same POST request multiple times creates multiple resources. PUT and DELETE are idempotent (calling them once has the same effect as calling them multiple times).","difficulty_score":3,"time_seconds":30,"tags":["idempotency","POST","HTTP"],"prerequisites":["rest_beg_001"],"common_mistakes":["Thinking POST is idempotent like PUT"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Glossary/Idempotent"],"real_world_context":"Lack of idempotency in POST causes duplicate payments on double-clicks."},
      {"question_id":"rest_beg_003","type":"mcq","question":"What does HTTP status code 404 mean?","options":["Internal Server Error","Unauthorised","Not Found","Bad Request"],"correct_answer":2,"explanation":"404 Not Found means the server cannot find the requested resource. 500 is Internal Server Error, 401 is Unauthorised, 400 is Bad Request.","difficulty_score":1,"time_seconds":30,"tags":["status_codes","404"],"prerequisites":[],"common_mistakes":["Confusing 404 with 401"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404"],"real_world_context":"404 is the most famous status code encountered in daily browsing."},
      {"question_id":"rest_beg_004","type":"true_false","question":"REST APIs can only return JSON.","correct_answer":False,"explanation":"REST is format-agnostic. While JSON is the most common format, REST APIs can return XML, plain text, HTML, or binary data like images, depending on the Accept header.","difficulty_score":2,"time_seconds":30,"tags":["JSON","content_negotiation","REST"],"prerequisites":[],"common_mistakes":["Thinking REST = JSON"],"learning_resources":["https://restfulapi.net/"],"real_world_context":"Enterprises often support both JSON and XML from the same endpoint."}
    ],
    "intermediate": [
      {"question_id":"rest_int_001","type":"mcq","question":"What is the semantic difference between PUT and PATCH?","options":["No difference","PUT updates partially; PATCH creates","PUT replaces the entire resource; PATCH applies a partial update","PATCH is faster"],"correct_answer":2,"explanation":"PUT requires the client to send the entire resource representation to replace the existing one. PATCH is used for partial updates, sending only the fields that need changing.","difficulty_score":5,"time_seconds":60,"tags":["PUT","PATCH","HTTP_methods"],"prerequisites":["rest_beg_001"],"common_mistakes":["Using PUT for partial updates (overwriting omitted fields with null)"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH"],"real_world_context":"PATCH saves bandwidth on massive JSON payloads during form saves."},
      {"question_id":"rest_int_002","type":"scenario","question":"An API pagination returns thousands of records. What is the most robust mechanism to send links to the next page?","options":["In the response body payload","As a JSON array","Using the HTTP Link header","In the URL fragment"],"correct_answer":2,"explanation":"The HTTP Link header (RFC 5988) is the standard RESTful way to provide pagination links (next, prev, first, last) separate from the resource payload, enabling generic client parsing.","difficulty_score":6,"time_seconds":75,"tags":["pagination","Link_header","headers"],"prerequisites":["rest_beg_001"],"common_mistakes":["Hardcoding pagination logic without standards"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link"],"real_world_context":"GitHub API uses Link headers extensively for pagination."},
      {"question_id":"rest_int_003","type":"code_debugging","question":"An API client receives 401 Unauthorised but they sent the correct token. What header is likely missing?","options":["Content-Type","Authorization: Bearer <token>","Accept: application/json","X-API-Key"],"correct_answer":1,"explanation":"Tokens (like JWTs) must typically be sent in the Authorization header using the 'Bearer' scheme. Just sending the token without the scheme or in the wrong header results in 401.","difficulty_score":5,"time_seconds":60,"tags":["authentication","headers","JWT"],"prerequisites":["rest_beg_003"],"common_mistakes":["Sending token in query string","Missing the Bearer keyword"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization"],"real_world_context":"Authentication header formatting is a daily source of integration bugs."},
      {"question_id":"rest_int_004","type":"mcq","question":"What is statelessness in REST?","options":["No database is used","The server stores no client context between requests","The client stores no state","All data is kept in memory"],"correct_answer":1,"explanation":"Statelessness means every request from client to server must contain all information needed to understand and process it. The server cannot rely on stored session context from previous requests.","difficulty_score":6,"time_seconds":60,"tags":["stateless","REST_principles","architecture"],"prerequisites":["rest_beg_004"],"common_mistakes":["Confusing DB state with session state"],"learning_resources":["https://restfulapi.net/statelessness/"],"real_world_context":"Stateless APIs enable horisontal scaling behind load balancers without sticky sessions."}
    ],
    "advanced": [
      {"question_id":"rest_adv_001","type":"scenario","question":"To prevent lost updates when two clients edit a resource simultaneously, what REST mechanism is used?","options":["Database locks","ETag and If-Match headers (Optimistic Concurrency Control)","Sessions","WebSockets"],"correct_answer":1,"explanation":"The server provides an ETag (hash of resource). The client sends it back via If-Match during PUT/PATCH. If the resource changed, ETags won't match, and the server returns 412 Precondition Failed, preventing an overwrite.","difficulty_score":8,"time_seconds":120,"tags":["concurrency","ETag","If-Match","optimistic_locking"],"prerequisites":["rest_int_001"],"common_mistakes":["Relying purely on last-write-wins"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag"],"real_world_context":"ETags are explicitly required for robust collaborative editing applications."},
      {"question_id":"rest_adv_002","type":"mcq","question":"What is HATEOAS in REST API design?","options":["Handling All Types of Errors on App Server","Hypermedia As The Engine Of Application State","High Availability Transmitting Errors Over API Sockets","Hypertext Application Transfer Environment OS"],"correct_answer":1,"explanation":"HATEOAS dictates that a REST client needs no prior knowledge of how to interact with an application beyond a generic understanding of hypermedia. The server provides links dynamically telling the client what actions are available.","difficulty_score":7,"time_seconds":90,"tags":["HATEOAS","hypermedia","REST_maturity"],"prerequisites":["rest_int_004"],"common_mistakes":["Building APIs that require out-of-band documentation without links"],"learning_resources":["https://en.wikipedia.org/wiki/HATEOAS"],"real_world_context":"HATEOAS represents Richardson Maturity Model Level 3, the pinnacle of true REST APIs."}
    ]
  }
}

html_skill = {
  "skill_id": "html_css",
  "skill_name": "HTML / CSS",
  "category": "frontend_development",
  "total_questions": 12,
  "levels": {
    "beginner": [
      {"question_id":"html_beg_001","type":"mcq","question":"Which tag is used for the largest heading in HTML?","options":["<header>","<h1>","<h6>","<head>"],"correct_answer":1,"explanation":"<h1> is the highest level (largest) heading element. <h6> is the smallest. <header> is a semantic container for introductory content. <head> contains metadata.","difficulty_score":1,"time_seconds":30,"tags":["tags","headings","html"],"prerequisites":[],"common_mistakes":["Using <header> instead of <h1>"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements"],"real_world_context":"Correct heading hierarchy is crucial for SEO and screen readers."},
      {"question_id":"html_beg_002","type":"code_output","question":"What does this HTML render?\n\n<a href=\"#contact\">Contact Us</a>","options":["Opens a new page","Scrolls to an element with id='contact'","Sends an email","Downloads a file"],"correct_answer":1,"explanation":"An anchor tag with an href starting with '#' targets an element on the same page by its ID, creating a jump link or scroll effect to that section.","difficulty_score":2,"time_seconds":30,"tags":["links","anchors","ids"],"prerequisites":["html_beg_001"],"common_mistakes":["Expecting it to open a new tab"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a"],"real_world_context":"Anchor links are the standard for single-page navigation menus."},
      {"question_id":"html_beg_003","type":"mcq","question":"Which CSS property changes text colour?","options":["text-color","font-color","color","background-color"],"correct_answer":2,"explanation":"The 'color' property sets the foreground (text) colour of an element. Neither 'text-color' nor 'font-color' exist in standard CSS.","difficulty_score":1,"time_seconds":30,"tags":["css","color","typography"],"prerequisites":[],"common_mistakes":["Using font-color (which doesn't exist)"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/CSS/color"],"real_world_context":"Color is one of the most frequently used CSS properties universally."},
      {"question_id":"html_beg_004","type":"true_false","question":"An id attribute must be unique within an entire HTML document.","correct_answer":True,"explanation":"IDs must be globally unique within an HTML document. Classes can be reused on multiple elements. Invalid HTML with duplicate IDs breaks JavaScript querySelector and CSS specificity.","difficulty_score":2,"time_seconds":30,"tags":["id","classes","attributes"],"prerequisites":["html_beg_001"],"common_mistakes":["Reusing IDs like classes"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id"],"real_world_context":"Duplicate IDs are the root cause of many elusive UI selection bugs."},
      {"question_id":"html_beg_005","type":"code_debugging","question":"Why is this image not accessible to screen readers?\n\n<img src=\"logo.png\">","options":["Missing alt attribute","Missing title attribute","Not wrapped in <a>","Format should be .jpg"],"correct_answer":0,"explanation":"Screen readers rely on the 'alt' attribute to describe images to visually impaired users. If an image is purely decorative, use alt=\"\" so screen readers ignore it.","difficulty_score":3,"time_seconds":45,"tags":["accessibility","img","alt"],"prerequisites":["html_beg_001"],"common_mistakes":["Using title instead of alt","Omitting alt entirely"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img"],"real_world_context":"Missing alt text fails Web Content Accessibility Guidelines (WCAG) compliance audits."}
    ],
    "intermediate": [
      {"question_id":"html_int_001","type":"mcq","question":"What is the CSS Box Model?","options":["A framework for responsive design","A grid system","The layout model containing margins, borders, padding, and the content itself","A way to draw 3D boxes"],"correct_answer":2,"explanation":"Every element is a rectangular box comprising, from outside to inside: Margin, Border, Padding, Content area. Understanding this is fundamental to all CSS layouts.","difficulty_score":4,"time_seconds":45,"tags":["css","box_model","layout"],"prerequisites":["html_beg_003"],"common_mistakes":["Confusing padding (inside) and margin (outside border)"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model"],"real_world_context":"Spacing bugs always trace back to box model misunderstandings."},
      {"question_id":"html_int_002","type":"scenario","question":"An element's width is 100px. Adding 20px padding makes it 140px wide. How do you stop padding from increasing total width?","options":["box-sizing: border-box","padding-collapse: true","width: calc(100px - 40px)","overflow: hidden"],"correct_answer":0,"explanation":"box-sizing: border-box tells the browser to include padding and border within the specified width. Instead of expanding, the inner content area shrinks to accommodate them.","difficulty_score":5,"time_seconds":60,"tags":["box_sizing","border_box","layout"],"prerequisites":["html_int_001"],"common_mistakes":["Manually calculating calc() dimensions"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing"],"real_world_context":"border-box is so useful it's standard practice to apply it to * universally in CSS resets."},
      {"question_id":"html_int_003","type":"code_output","question":"What does 'display: none' do vs 'visibility: hidden'?","options":["No difference","display: none removes element from document flow; visibility hides but keeps its space","display: none hides; visibility deletes","visibility is for text only"],"correct_answer":1,"explanation":"display: none makes it as if the element doesn't exist; surrounding elements collapse. visibility: hidden makes the element invisible but it still occupies physical space in the layout.","difficulty_score":4,"time_seconds":45,"tags":["display","visibility","css"],"prerequisites":["html_beg_003"],"common_mistakes":["Thinking both collapse layout space"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/CSS/display"],"real_world_context":"Use visibility: hidden to preserve structural alignment when elements pop in/out."},
      {"question_id":"html_int_004","type":"mcq","question":"Which CSS selector targets elements with class A *inside* elements with class B?","options":[".A .B",".B .A",".A>.B",".A, .B"],"correct_answer":1,"explanation":".B .A (descendant selector) targets .A elements inside .B elements. .B > .A (child selector) targets only direct children. .A, .B targets both independently.","difficulty_score":4,"time_seconds":45,"tags":["selectors","specificity","css"],"prerequisites":["html_beg_004"],"common_mistakes":["Mixing descendant and child selectors","Incorrect parent-child order in selector string"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/CSS/Descendant_combinator"],"real_world_context":"Complex SCSS nesting relies on understanding raw CSS descendant selectors."},
      {"question_id":"html_int_005","type":"code_debugging","question":"Why isn't this pseudo-element visible?\n\n.box::before { background: red; width: 10px; height: 10px; display: block; }","options":["Must use :before","content property is missing","Missing position absolute","Pseudo-elements cannot have dimensions"],"correct_answer":1,"explanation":"Pseudo-elements (::before / ::after) will not render at all unless a 'content' property evaluates to something, even an empty string (content: \"\").","difficulty_score":6,"time_seconds":60,"tags":["pseudo_elements","content","css"],"prerequisites":["html_beg_003"],"common_mistakes":["Forgetting the content property","Using ::before for structural HTML replacements"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/CSS/::before"],"real_world_context":"::before and ::after are essential for CSS-only tooltips, icons, and decorative shapes."}
    ],
    "advanced": [
      {"question_id":"html_adv_001","type":"scenario","question":"A fixed-position navigation bar covers page content when scrolling to jump links. What is the modern CSS fix?","options":["JavaScript scroll offset","margin-top on body","scroll-padding-top on html","position: relative instead"],"correct_answer":2,"explanation":"scroll-padding-top on the scroll container (often html) offsets the scroll position for anchor jump links, perfectly aligning the content smoothly below fixed headers without messy JavaScript.","difficulty_score":8,"time_seconds":90,"tags":["scroll","sticky","modern_css"],"prerequisites":["html_beg_002","html_int_001"],"common_mistakes":["Using complex JS calculations for scroll offset","Using negative margins"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding-top"],"real_world_context":"This replaces decades of brittle JavaScript offset hacks for fixed headers."},
      {"question_id":"html_adv_002","type":"mcq","question":"In CSS Flexbox, what does 'align-items' control?","options":["Alignment along the main axis (e.g., horizontal in a row)","Alignment along the cross axis (e.g., vertical in a row)","Spacing between elements","Wrapping of flex items"],"correct_answer":1,"explanation":"align-items aligns flex items along the cross axis (perpendicular to flex-direction). justify-content aligns items along the main axis.","difficulty_score":7,"time_seconds":60,"tags":["flexbox","alignment","layout"],"prerequisites":["html_int_001"],"common_mistakes":["Confusing justify-content (main) with align-items (cross)"],"learning_resources":["https://css-tricks.com/snippets/css/a-guide-to-flexbox/"],"real_world_context":"Centering a div perfectly uses both justify-content: center and align-items: center."}
    ]
  }
}

js_fe_skill = {
  "skill_id": "javascript_frontend",
  "skill_name": "JavaScript (Frontend)",
  "category": "frontend_development",
  "total_questions": 15,
  "levels": {
    "beginner": [
      {"question_id":"jsfe_beg_001","type":"mcq","question":"Which method selects the FIRST element with a specific CSS class?","options":["getElementByClass()","querySelectorAll()","querySelector()","getElementsByClassName()"],"correct_answer":2,"explanation":"querySelector('.class') returns the first matching element. querySelectorAll returns a NodeList of all matches. getElementsByClassName returns an HTMLCollection of all matches.","difficulty_score":2,"time_seconds":30,"tags":["DOM","selectors"],"prerequisites":[],"common_mistakes":["Using querySelectorAll for a single element","Forgetting the dot prefix for classes"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector"],"real_world_context":"querySelector is the modern, versatile standard for DOM querying."},
      {"question_id":"jsfe_beg_002","type":"code_output","question":"What does this code do?\n\ndocument.getElementById('btn').addEventListener('click', () => alert('Hi'));","options":["Defines a function","Shows an alert immediately","Shows alert when element with ID 'btn' is clicked","Throws an error"],"correct_answer":2,"explanation":"addEventListener attaches a click event listener to the button. When a click occurs on that specific element, the arrow function executes.","difficulty_score":2,"time_seconds":30,"tags":["events","DOM","listeners"],"prerequisites":["jsfe_beg_001"],"common_mistakes":["Thinking alert shows on load"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener"],"real_world_context":"The foundational method for making static HTML pages interactive."},
      {"question_id":"jsfe_beg_003","type":"mcq","question":"Which property gets or sets the HTML markup inside an element?","options":["innerText","textContent","innerHTML","htmlContent"],"correct_answer":2,"explanation":"innerHTML returns the HTML content as a string. Changing it recalculates the DOM for that element. textContent gets only the raw text, stripping tags.","difficulty_score":2,"time_seconds":30,"tags":["DOM","manipulation","innerHTML"],"prerequisites":[],"common_mistakes":["Using innerText instead of innerHTML when tags are needed"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML"],"real_world_context":"Unsanitised innerHTML usage is the leading cause of XSS attacks."},
      {"question_id":"jsfe_beg_004","type":"true_false","question":"Local storage data clears automatically when the browser tab is closed.","correct_answer":False,"explanation":"localStorage persists indefinitely across sessions. sessionStorage clears when the page session ends (e.g., tab closed). Cookies have configurable expiry dates.","difficulty_score":2,"time_seconds":30,"tags":["storage","browser_api"],"prerequisites":[],"common_mistakes":["Confusing local and session storage"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage"],"real_world_context":"Preferences like 'dark mode' are kept in localStorage to persist across visits."},
      {"question_id":"jsfe_beg_005","type":"mcq","question":"How do you abort the default form submission (page reload) in JavaScript?","options":["return false","event.preventDefault()","event.stopPropagation()","form.stop()"],"correct_answer":1,"explanation":"preventDefault() stops the browser's default action (like submitting a form or following a link). stopPropagation() stops event bubbling without affecting default actions.","difficulty_score":3,"time_seconds":30,"tags":["events","forms","preventDefault"],"prerequisites":["jsfe_beg_002"],"common_mistakes":["Using stopPropagation to stop form submits"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault"],"real_world_context":"preventDefault is mandatory for Single Page Application (SPA) form handling."},
      {"question_id":"jsfe_beg_006","type":"code_debugging","question":"Why does 'this.value' log undefined?\n\nbtn.addEventListener('click', () => console.log(this.value));","options":["Missing default prevent","Arrow functions don't bind 'this' to the event target","Arrow requires return statement","Value must be .text"],"correct_answer":1,"explanation":"Arrow functions capture `this` from the outer lexical scope (usually Window). Regular function declarations bind `this` to the element that fired the event. Use `event.target.value` instead.","difficulty_score":4,"time_seconds":45,"tags":["arrow_functions","this","events"],"prerequisites":["jsfe_beg_002"],"common_mistakes":["Using arrow functions as event handlers relying on local 'this'"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions"],"real_world_context":"Migrating jQuery event handlers to ES6 often triggers this exact bug."}
    ],
    "intermediate": [
      {"question_id":"jsfe_int_001","type":"mcq","question":"What is Event Delegation?","options":["Passing events between windows","Capturing unhandled errors","Attaching one event listener to a parent to handle events on multiple children using event propagation","Delegating UI updates to Web Workers"],"correct_answer":2,"explanation":"Because events 'bubble' up the DOM tree, one listener on a parent (e.g. <ul>) can catch click events originating from its children (<li>), checking event.target to act appropriately. This saves massive memory vs thousands of listeners.","difficulty_score":5,"time_seconds":60,"tags":["events","delegation","performance"],"prerequisites":["jsfe_beg_002"],"common_mistakes":["Adding listeners in a loop to 1000 row items"],"learning_resources":["https://javascript.info/event-delegation"],"real_world_context":"Mandatory pattern for dynamic UI lists where items are added/removed often."},
      {"question_id":"jsfe_int_002","type":"code_output","question":"What triggers the error 'Cross-Origin Request Blocked'?","options":["CORS policy blocking XHR/fetch to a different domain without appropriate headers","Syntax error in external script","Loading an image over HTTP on an HTTPS site","SSL expiration"],"correct_answer":0,"explanation":"Browsers enforce the Same-Origin Policy. Fetching data from a different domain requires the server to explicitly allow it by sending Access-Control-Allow-Origin headers (CORS).","difficulty_score":5,"time_seconds":45,"tags":["CORS","security","fetch"],"prerequisites":[],"common_mistakes":["Thinking CORS is a client-side fix (it requires server configuration)"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS"],"real_world_context":"The #1 most misunderstood feature block for frontend developers integrating new APIs."},
      {"question_id":"jsfe_int_003","type":"scenario","question":"A scroll listener makes 30 DOM updates per second, causing lag. Best mitigation?","options":["Use a Web Worker","Debounce or throttle the listener","Use requestAnimationFrame instead of DOM","Remove CSS animations"],"correct_answer":1,"explanation":"Throttling limits listener execution to once every X ms. Debouncing waits until the user stops scrolling. Both drastically reduce rapid-fire executions solving the performance bottleneck.","difficulty_score":6,"time_seconds":75,"tags":["performance","debounce","throttle","events"],"prerequisites":["jsfe_beg_002"],"common_mistakes":["Optimising DOM updates before throttling the event source"],"learning_resources":["https://css-tricks.com/debouncing-throttling-explained-examples/"],"real_world_context":"Search auto-completes and infinite scrolls require debouncing/throttling respectively."},
      {"question_id":"jsfe_int_004","type":"mcq","question":"What does window.requestAnimationFrame do?","options":["Animates CSS automatically","Tells browser to perform animation before the next repaint for smooth 60fps visuals","A polyfill for canvas","Pauses execution for 1 frame"],"correct_answer":1,"explanation":"rAF schedules a callback right before the browser's next repaint, synchronising changes with the monitor's refresh rate (typically 60fps). This avoids jank caused by setInterval drifting out of sync.","difficulty_score":6,"time_seconds":60,"tags":["animation","requestAnimationFrame","performance"],"prerequisites":["jsfe_int_003"],"common_mistakes":["Using setInterval for high-performance animations"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame"],"real_world_context":"Canvas render loops and smooth scrolling engines run purely on rAF."},
      {"question_id":"jsfe_int_005","type":"true_false","question":"Mutating the DOM forces a layout reflow.","correct_answer":True,"explanation":"Changing geometry (width, height, adding nodes) triggers a layout reflow and repaint. Reading layout properties (offsetWidth) immediately after changing them forces synchronous reflows, killing performance.","difficulty_score":6,"time_seconds":45,"tags":["DOM","reflow","repaint","performance"],"prerequisites":["jsfe_int_001"],"common_mistakes":["Changing and reading DOM properties back-to-back in loops"],"learning_resources":["https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing"],"real_world_context":"Layout thrashing makes powerful modern machines feel entirely unresponsive on heavy sites."},
      {"question_id":"jsfe_int_006","type":"mcq","question":"Which API provides off-main-thread execution for heavy computation in browsers?","options":["Service Workers","WebSockets","Web Workers","LocalStorage"],"correct_answer":2,"explanation":"Web Workers run JavaScript logic on separate background threads, keeping the main UI thread unblocked during heavy computation (e.g., image processing or massive JSON parsing). Service workers focus on caching and offline capabilities.","difficulty_score":5,"time_seconds":60,"tags":["web_workers","concurrency","performance"],"prerequisites":[],"common_mistakes":["Confusing Web Workers with Service Workers"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API"],"real_world_context":"Critical for SPAs doing local ML inference or complex aggregations."}
    ],
    "advanced": [
      {"question_id":"jsfe_adv_001","type":"scenario","question":"An SPA works on reload, but back/forward browser buttons don't update the UI. What API is missing?","options":["Session History Management (History API)","Local Storage API","IndexedDB","Service Workers"],"correct_answer":0,"explanation":"Client-side routing relies on the History API (pushState, replaceState) to change the URL without a page reload. Handling the 'popstate' event is required to respond when the user clicks browser navigation buttons.","difficulty_score":7,"time_seconds":90,"tags":["history_api","routing","SPA"],"prerequisites":["jsfe_int_001"],"common_mistakes":["Changing window.location (causes reload) instead of pushState"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/API/History_API"],"real_world_context":"The foundational architecture underneath Vue Router and React Router."},
      {"question_id":"jsfe_adv_002","type":"mcq","question":"What describes a Service Worker?","options":["A background script that acts as a network proxy, intercepting requests for offline caching","A thread dedicated strictly to UI animation","A background database agent","An automated test runner"],"correct_answer":0,"explanation":"Service Workers intercept network requests. They can respond from cache to enable offline mode in PWAs. They run separately from the main page and have no DOM access.","difficulty_score":8,"time_seconds":90,"tags":["service_workers","PWA","offline"],"prerequisites":["jsfe_int_006"],"common_mistakes":["Trying to manipulate the DOM from a Service Worker"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API"],"real_world_context":"Service Workers power progressive web apps (PWAs) and push notifications."},
      {"question_id":"jsfe_adv_003","type":"code_analysis","question":"What does intersectionObserver.observe(element) accomplish efficiently?","options":["Detects when an element changes size","Checks when an element enters or exits the viewport","Observes DOM mutations on the element","Prevents CSS intersections"],"correct_answer":1,"explanation":"IntersectionObserver efficiently detects when elements scroll into view asynchronously. Older techniques used costly scroll event listeners + getBoundingClientRect, which caused heavy main-thread jank.","difficulty_score":7,"time_seconds":90,"tags":["IntersectionObserver","viewport","lazy_loading"],"prerequisites":["jsfe_int_005"],"common_mistakes":["Using scroll handlers for simple viewport checks"],"learning_resources":["https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API"],"real_world_context":"Native lazy loading of images and infinite scrolling feeds use IntersectionObserver."}
    ]
  }
}

react_skill = {
  "skill_id": "react",
  "skill_name": "React",
  "category": "frontend_development",
  "total_questions": 15,
  "levels": {
    "beginner": [
      {"question_id":"react_beg_001","type":"mcq","question":"What is JSX?","options":["A new Javascript standard","A syntax extension that looks like HTML for writing UI in JavaScript","A CSS preprocessor","A database query language"],"correct_answer":1,"explanation":"JSX is syntax sugar that compiles into React.createElement() calls. It allows developers to write declarative UI structure in tandem with JavaScript logic easily.","difficulty_score":1,"time_seconds":30,"tags":["JSX","fundamentals","react"],"prerequisites":[],"common_mistakes":["Thinking JSX is raw HTML running natively in browser"],"learning_resources":["https://reactjs.org/docs/introducing-jsx.html"],"real_world_context":"Browsers cannot parse JSX directly; it requires compilation via Babel or SWC."},
      {"question_id":"react_beg_002","type":"mcq","question":"Which React hook manages state in functional components?","options":["useEffect","useReducer","useState","useContext"],"correct_answer":2,"explanation":"useState returns an array with the current state value and a function to update it. useEffect manages side effects, useContext manages context.","difficulty_score":1,"time_seconds":30,"tags":["useState","hooks","state"],"prerequisites":[],"common_mistakes":["Confusing state with props"],"learning_resources":["https://reactjs.org/docs/hooks-state.html"],"real_world_context":"The vast majority of dynamic component data resides in useState."},
      {"question_id":"react_beg_003","type":"true_false","question":"Props in React are mutable and can be changed by the receiving component.","correct_answer":False,"explanation":"Props are strictly read-only (immutable). A component must never modify its own props. If interactive data is needed, state must be used instead.","difficulty_score":2,"time_seconds":30,"tags":["props","data_flow"],"prerequisites":["react_beg_001"],"common_mistakes":["Attempting to update props like props.value = 2"],"learning_resources":["https://reactjs.org/docs/components-and-props.html"],"real_world_context":"Unidirectional data flow guarantees predictability in complex app state."},
      {"question_id":"react_beg_004","type":"code_output","question":"When mapping an array to JSX elements, what prop is REQUIRED?","options":["data-id","index","key","uuid"],"correct_answer":2,"explanation":"React requires a unique 'key' prop on elements inside an array mapping. This helps React identify which items changed, were added, or were removed, optimising reconciliation.","difficulty_score":2,"time_seconds":30,"tags":["lists","keys","mapping"],"prerequisites":["react_beg_001"],"common_mistakes":["Using array index as key for lists that can reorder"],"learning_resources":["https://reactjs.org/docs/lists-and-keys.html"],"real_world_context":"Missing keys trigger console warnings and cause subtle list-rendering bugs."},
      {"question_id":"react_beg_005","type":"code_debugging","question":"Why doesn't the component update visually?\n\n```js\nconst [val, setVal] = useState([]);\nval.push(1);\nsetVal(val);\n```","options":["push doesn't work on state","state variables are const","setVal is missing an await","React compares array references; modifying and passing the same object reference won't trigger re-render"],"correct_answer":3,"explanation":"React uses Object.is() for state comparison. Mutating an array and passing the exact same array reference back means React sees 'no change'. You must pass a new reference: setVal([...val, 1]).","difficulty_score":4,"time_seconds":60,"tags":["useState","mutability","references"],"prerequisites":["react_beg_002"],"common_mistakes":["Mutating arrays/objects in state directly"],"learning_resources":["https://react.dev/learn/updating-arrays-in-state"],"real_world_context":"Direct state mutation is the #1 cause of React UI failing to update."}
    ],
    "intermediate": [
      {"question_id":"react_int_001","type":"mcq","question":"What does the dependency array in useEffect control?","options":["When the effect function re-runs","Which components re-render","How many times loop runs","Order of execution"],"correct_answer":0,"explanation":"React skips the effect if the dependencies haven't changed between renders. An empty array [] means it runs only once on mount. No array means it runs every render.","difficulty_score":5,"time_seconds":45,"tags":["useEffect","hooks","lifecycle"],"prerequisites":["react_beg_002"],"common_mistakes":["Omitting dependencies leading to infinite loops","Object references in dependency arrays causing loops"],"learning_resources":["https://react.dev/reference/react/useEffect"],"real_world_context":"Misconfigured dependency arrays account for most infinite loop crashes in React."},
      {"question_id":"react_int_002","type":"scenario","question":"A parent renders frequently. Which hook prevents an expensive child component from re-rendering unless its props change?","options":["useMemo","React.memo","useCallback","useEffect"],"correct_answer":1,"explanation":"React.memo is a higher-order component that memoises the entire child component. useMemo memoises computed values; useCallback memoises function identities.","difficulty_score":5,"time_seconds":60,"tags":["performance","memoization","React.memo"],"prerequisites":["react_beg_003"],"common_mistakes":["Using useMemo to wrap a component","Overusing React.memo for cheap components"],"learning_resources":["https://react.dev/reference/react/memo"],"real_world_context":"Memoizing large data tables or charts avoids lagging main-thread interactions."},
      {"question_id":"react_int_003","type":"code_debugging","question":"Why might setting state in an API response cause an error on an unmounted component?","options":["API is slow","Memory leak; component unmounted before promise resolved","State is read-only","React 18 ignores API calls"],"correct_answer":1,"explanation":"If a component begins an async fetch but unmounts (e.g., user navigates away) before it completes, calling setState on the unmounted component attempts to update non-existent UI, risking memory leaks. Use AbortController.","difficulty_score":6,"time_seconds":75,"tags":["useEffect","async","memory_leaks","unmount"],"prerequisites":["react_int_001"],"common_mistakes":["Not returning cleanup functions in useEffect"],"learning_resources":["https://react.dev/learn/synchronizing-with-effects#fetching-data"],"real_world_context":"Cleanup handling on navigation reduces spurious React runtime warnings."},
      {"question_id":"react_int_004","type":"mcq","question":"What does Context API solve?","options":["Database connections","Prop drilling (passing props through many deep layers)","State mutation bugs","Server-side rendering"],"correct_answer":1,"explanation":"Context provides a way to pass data through the component tree without having to pass props down manually at every level. Useful for globals like current authenticated user or UI theme.","difficulty_score":4,"time_seconds":45,"tags":["context_api","prop_drilling","state_management"],"prerequisites":["react_int_002"],"common_mistakes":["Using Context as a replacement for ALL state (causes over-rendering)"],"learning_resources":["https://react.dev/learn/passing-data-deeply-with-context"],"real_world_context":"Context replaces Redux for simple global states like i18n locales and theming."},
      {"question_id":"react_int_005","type":"code_output","question":"If setCounter(count + 1) is called 3 times synchronously in a row, what matters in React 18?","options":["Counter increments by 3","Counter increments by 1 due to batching","Throws a warning","Render triggers 3 times"],"correct_answer":1,"explanation":"React automatically batches state updates for performance. 3 synchronous calls using the old value execute as setting the exact same new value 3 times. Use functional updates: setCounter(prev => prev + 1).","difficulty_score":6,"time_seconds":60,"tags":["batching","useState","react18"],"prerequisites":["react_beg_002"],"common_mistakes":["Not using functional updates for sequential state dependencies"],"learning_resources":["https://react.dev/learn/queueing-a-series-of-state-updates"],"real_world_context":"Batching awareness is critical to avoid race conditions in form submitting logic."}
    ],
    "advanced": [
      {"question_id":"react_adv_001","type":"scenario","question":"An application needs complex state logic involving multiple sub-values dependent on previous states. useState is getting tangled. Best fix?","options":["Context API","useReducer","Multiple useEffects","Global variables"],"correct_answer":1,"explanation":"useReducer is preferable to useState when state logic involves complex sub-values or the next state depends on the previous one. It centralises update logic in a pure reducer function, akin to Redux.","difficulty_score":7,"time_seconds":90,"tags":["useReducer","state_arch","complex_state"],"prerequisites":["react_int_005"],"common_mistakes":["Writing spaghetti code with 10 independent useStates"],"learning_resources":["https://react.dev/learn/extracting-state-logic-into-a-reducer"],"real_world_context":"useReducer is used for complex search filters and multi-step form data management."},
      {"question_id":"react_adv_002","type":"mcq","question":"What is React Server Components (RSC)?","options":["A Node.js backend framework","Components that render exclusively on the server, sending HTML/streamed UI without JavaScript bundles to the client","Components that host APIs","A database ORM"],"correct_answer":1,"explanation":"RSCs execute and render only on the server, producing UI output directly. This drastically reduces client-side JavaScript bundles, allowing direct server/DB access without dedicated API endpoints. Available in Next.js App Router.","difficulty_score":8,"time_seconds":120,"tags":["RSC","server_components","architecture","nextjs"],"prerequisites":["react_int_004"],"common_mistakes":["Using React hooks (useState, useEffect) in Server Components (illegal)"],"learning_resources":["https://react.dev/reference/rsc/server-components"],"real_world_context":"RSC is the architectural paradigm shift driving Next.js 13+ and modern React landscapes."},
      {"question_id":"react_adv_003","type":"code_analysis","question":"Why wrap a function in useCallback before passing it as a prop to a memoized child?","options":["To execute it faster","To prevent the function identity from changing every render, which would break the child's memoization","To compress memory","To bind 'this'"],"correct_answer":1,"explanation":"Functions in JS are re-created every render. Passing a new function reference to a React.memo child breaks its memoization check (props changed). useCallback ensures the function reference remains identical across renders.","difficulty_score":8,"time_seconds":120,"tags":["useCallback","performance","referential_equality"],"prerequisites":["react_int_002"],"common_mistakes":["Using useCallback on primitive props (unnecessary)","Forgetting dependency arrays in useCallback"],"learning_resources":["https://react.dev/reference/react/useCallback"],"real_world_context":"useCallback + React.memo together resolve 90% of excessive render lag trees."}
    ]
  }
}

skills = [rest_skill, html_skill, js_fe_skill, react_skill]
