ts_skill = {
  "skill_id": "typescript",
  "skill_name": "TypeScript",
  "category": "frontend_development",
  "total_questions": 8,
  "levels": {
    "beginner": [
      {"question_id":"ts_beg_001","type":"mcq","question":"How do you specify that an array only contains strings in TypeScript?","options":["Array<string> or string[]","[string]","array: string","stringArray"],"correct_answer":0,"explanation":"Both `string[]` and `Array<string>` are valid ways to type an array of strings in TypeScript. `[string]` is a tuple type containing exactly one string.","difficulty_score":2,"time_seconds":30,"tags":["arrays","types","syntax"],"prerequisites":[],"common_mistakes":["Using [string] for a dynamic array"],"learning_resources":["https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#arrays"],"real_world_context":"Array typing is essential for robust API response handling."},
      {"question_id":"ts_beg_002","type":"true_false","question":"TypeScript 'any' type maintains type safety by behaving like 'unknown'.","correct_answer":False,"explanation":"'any' completely disables type checking for a variable, allowing any operation on it. 'unknown' is the type-safe counterpart that forces you to perform a type check before operating on it.","difficulty_score":3,"time_seconds":30,"tags":["any","unknown","type_safety"],"prerequisites":[],"common_mistakes":["Overusing 'any' instead of 'unknown' to bypass errors"],"learning_resources":["https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#any"],"real_world_context":"The 'any' type defeats the purpose of TS and is banned in strict codebases."},
      {"question_id":"ts_beg_003","type":"mcq","question":"Which keyword defines a custom type structure without creating a class?","options":["struct","interface","blueprint","namespace"],"correct_answer":1,"explanation":"An 'interface' defines the shape of an object (properties and methods) purely for type checking. It is erased during compilation to JavaScript. 'type' aliases can also be used.","difficulty_score":2,"time_seconds":30,"tags":["interface","types","oop"],"prerequisites":[],"common_mistakes":["Using classes when only type checking is needed"],"learning_resources":["https://www.typescriptlang.org/docs/handbook/2/objects.html"],"real_world_context":"Interfaces are the primary way to define API response structures in React apps."}
    ],
    "intermediate": [
      {"question_id":"ts_int_001","type":"mcq","question":"What does the '?' operator do in an interface property declaration?","options":["Makes it optional","Makes it nullable","Throws an error if missing","Casts it to boolean"],"correct_answer":0,"explanation":"Appending '?' to a property name (e.g. `age?: number`) makes the property optional. Objects can be assigned to the interface without including that property. Its type becomes `number | undefined`.","difficulty_score":4,"time_seconds":45,"tags":["optional","interfaces","syntax"],"prerequisites":["ts_beg_003"],"common_mistakes":["Confusing optional '?' with nullable 'number | null'"],"learning_resources":["https://www.typescriptlang.org/docs/handbook/2/objects.html#optional-properties"],"real_world_context":"Optional properties handle sparse API updates (PATCH endpoints)."},
      {"question_id":"ts_int_002","type":"code_debugging","question":"Why does this result in a TS error?\n\nconst user = { name: 'Alice' } as const;\nuser.name = 'Bob';","options":["'const' objects cannot be modified in JS","as const makes all properties readonly primitives","user is not typed","Missing semi-colon"],"correct_answer":1,"explanation":"The 'as const' assertion tells TypeScript to treat the object as completely immutable (readonly) and use narrow literal types (type is 'Alice', not string). Modifying properties throws a TS error.","difficulty_score":5,"time_seconds":60,"tags":["as_const","readonly","literal_types"],"prerequisites":["ts_beg_001"],"common_mistakes":["Thinking 'as const' is standard JS const"],"learning_resources":["https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions"],"real_world_context":"'as const' is used for defining strict configuration objects or Redux action types."},
      {"question_id":"ts_int_003","type":"scenario","question":"A function accepts a string or a number. You need to call .toUpperCase() only if it's a string. Best TS approach?","options":["Cast as string (x as string).toUpperCase()","Type Guard: typeof x === 'string'","Try/catch","Use 'any'"],"correct_answer":1,"explanation":"A type guard (typeof x === 'string') narrows the union type inside the if-block. TypeScript acts intelligently and allows string methods only within that truthy branch safely.","difficulty_score":6,"time_seconds":60,"tags":["type_guards","narrowing","union_types"],"prerequisites":["ts_int_001"],"common_mistakes":["Using type assertions (as) blindly, crashing at runtime"],"learning_resources":["https://www.typescriptlang.org/docs/handbook/2/narrowing.html#typeof-type-guards"],"real_world_context":"Type narrowing prevents 'toUpperCase is not a function' production crashes."}
    ],
    "advanced": [
      {"question_id":"ts_adv_001","type":"scenario","question":"You have a User interface. You need a type representing a User where all properties are optional (for updates). Which Utility type?","options":["Partial<User>","Record<string, any>","Omit<User, never>","Pick<User, 'all'>"],"correct_answer":0,"explanation":"Partial<T> automatically constructs a type where every property of T is marked as optional ('?'). It is the standard utility type for creating update/patch payloads.","difficulty_score":7,"time_seconds":90,"tags":["utility_types","Partial","mapped_types"],"prerequisites":["ts_int_001"],"common_mistakes":["Manually writing a duplicate 'UpdateUser' interface"],"learning_resources":["https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype"],"real_world_context":"Partial is ubiquitous in API client generation and state partial updates."},
      {"question_id":"ts_adv_002","type":"code_analysis","question":"What does this advanced type extract?\n\ntype Return<T> = T extends (...args: any[]) => infer R ? R : any;","options":["Throws syntax error","The parameter types of a function","The return type of a function","A generic interface"],"correct_answer":2,"explanation":"This implements the built-in ReturnType<T> utility. It uses conditional types with the 'infer' keyword to extract the output type (R) of any function signature passed to it.","difficulty_score":9,"time_seconds":120,"tags":["conditional_types","infer","ReturnType","advanced_types"],"prerequisites":["ts_beg_001"],"common_mistakes":["Confusing generic parameters with infer extraction"],"learning_resources":["https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#inferring-within-conditional-types"],"real_world_context":"Inferring return types is crucial for strict Redux/Zustand slice typing."}
    ]
  }
}

etl_skill = {
  "skill_id": "data_pipelines_etl",
  "skill_name": "Data Pipelines/ETL",
  "category": "data_engineering",
  "total_questions": 12,
  "levels": {
    "beginner": [
      {"question_id":"etl_beg_001","type":"mcq","question":"What does ETL stand for?","options":["Export Transform Load","Extract Transform Load","External Transfer Log","Extract Transfer Loop"],"correct_answer":1,"explanation":"Extract (read from sources), Transform (clean, join, aggregate), and Load (write to destination like a data warehouse) is the standard data integration process.","difficulty_score":1,"time_seconds":30,"tags":["ETL","fundamentals","data_engineering"],"prerequisites":[],"common_mistakes":["Thinking E stands for Export"],"learning_resources":["https://www.databricks.com/glossary/extract-transform-load"],"real_world_context":"ETL powers all BI and analytics reporting."},
      {"question_id":"etl_beg_002","type":"true_false","question":"An idempotent ETL pipeline will produce duplicate records if executed twice for the same day.","correct_answer":False,"explanation":"Idempotency means running a job once has exactly the same effect as running it multiple times. A well-designed idempotent ETL job uses UPSERT (MERGE) or DELETE/INSERT to avoid duplicating rows on rerun.","difficulty_score":3,"time_seconds":45,"tags":["idempotency","reruns","data_quality"],"prerequisites":["etl_beg_001"],"common_mistakes":["Using blind INSERTs making pipelines non-idempotent"],"learning_resources":["https://docs.getdbt.com/terms/idempotent"],"real_world_context":"Idempotency allows engineers to safely click 'retry' after an Airflow job failure."},
      {"question_id":"etl_beg_003","type":"mcq","question":"What is a DAG in the context of Apache Airflow?","options":["Data Aggregation Group","Directed Acyclic Graph","Distributed Application Gateway","Database Access Generator"],"correct_answer":1,"explanation":"A Directed Acyclic Graph represents an ETL workflow without loops. Tasks are nodes, and dependencies are directed edges. Tasks cannot form cycles (loops).","difficulty_score":2,"time_seconds":30,"tags":["Airflow","DAG","orchestration"],"prerequisites":[],"common_mistakes":["Thinking DAG applies only to Spark"],"learning_resources":["https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/dags.html"],"real_world_context":"DAGs are the industry standard way to define data pipeline dependencies."},
      {"question_id":"etl_beg_004","type":"mcq","question":"Which process model is ELT?","options":["Extract Load Transform","Extract Live Transform","Event Log Trigger","Export Local Transfer"],"correct_answer":0,"explanation":"ELT loads raw data directly into the data warehouse, then leverages the warehouse's powerful compute to perform SQL-based transformations. It replaces ETL for modern cloud warehouses alongside tools like dbt.","difficulty_score":2,"time_seconds":30,"tags":["ELT","ETL_vs_ELT","dbt"],"prerequisites":["etl_beg_001"],"common_mistakes":["Confusing the Transform phase order"],"learning_resources":["https://www.fivetran.com/blog/etl-vs-elt"],"real_world_context":"ELT (via Fivetran + Snowflake + dbt) is the dominant modern data stack paradigm."},
      {"question_id":"etl_beg_005","type":"code_output","question":"An Airflow task has `retries=3`. How many maximum times can the task execute during a single DAG run instance?","options":["1","3","4","Unlimited"],"correct_answer":2,"explanation":"It executes exactly 1 time initially. If it fails, it will retry up to 3 times, meaning 4 total executions maximum.","difficulty_score":3,"time_seconds":45,"tags":["Airflow","retries","tasks"],"prerequisites":["etl_beg_003"],"common_mistakes":["Thinking retries means total executions (3)"],"learning_resources":["https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/tasks.html#task-instances"],"real_world_context":"Airflow retries combined with idempotency handle transient API/DB failures gracefully."}
    ],
    "intermediate": [
      {"question_id":"etl_int_001","type":"scenario","question":"An incremental data pipeline reads order data updated in the last 24 h. Yesterday it crashed, and today you manually rerun it. What data is processed?","options":["Today's data only, losing yesterday's updates","Both days if dynamic watermarking (e.g. execution_date) is used correctly","Duplicate rows for today","Complete historical reload"],"correct_answer":1,"explanation":"An incremental pipeline should rely on the orchestration tool's logical execution date (like Airflow's data_interval_start/end), not system currently wall-clock time. If triggered for yesterday, it processes yesterday's slice.","difficulty_score":6,"time_seconds":75,"tags":["incremental","backfilling","execution_date"],"prerequisites":["etl_beg_002"],"common_mistakes":["Using CURRENT_DATE() inside the SQL, breaking past reruns/backfills"],"learning_resources":["https://airflow.apache.org/docs/apache-airflow/stable/faq.html#what-s-the-deal-with-start-date"],"real_world_context":"Airflow execution dates allow perfect historical backfills without changing code."},
      {"question_id":"etl_int_002","type":"mcq","question":"What is Change Data Capture (CDC)?","options":["A feature to capture DB schema changes","Reading database transaction logs to stream rows inserted/updated/deleted to downstream systems in near real-time","Capturing changed git files","A batch processing technique"],"correct_answer":1,"explanation":"CDC tools (like Debezium) tap into database binlogs/WALs, capturing row-level changes sequentially as a stream of events, without running heavy select queries on the source DB.","difficulty_score":5,"time_seconds":60,"tags":["CDC","streaming","Debezium"],"prerequisites":["etl_beg_004"],"common_mistakes":["Thinking CDC is just a daily timestamp-based SELECT"],"learning_resources":["https://debezium.io/documentation/faq/"],"real_world_context":"CDC is the gold standard for replicating operational DBs to analytical DBs without impacting prod."},
      {"question_id":"etl_int_003","type":"code_debugging","question":"Why might `SELECT * FROM source_events WHERE updated_at > last_run_time` miss records?","options":["updated_at isn't indexed","Source system commits long-running transactions with older updated_at timestamps AFTER the ETL run completes","Timezone differences only","SQL doesn't support > on timestamps"],"correct_answer":1,"explanation":"Transactions that started before `last_run_time` but committed after it will have an older timestamp. The subsequent ETL run uses the new `last_run_time` and skips these late-arriving commits. CDC or overlap windows solve this.","difficulty_score":6,"time_seconds":75,"tags":["incremental_logic","ETL_gotchas","timestamps"],"prerequisites":["etl_beg_004"],"common_mistakes":["Ignoring transaction isolation properties in batch ETL"],"learning_resources":["https://www.confluent.io/en-gb/blog/no-more-silos-how-to-integrate-your-databases-with-apache-kafka-and-cdc/"],"real_world_context":"Missing late-arriving data in timestamp-based ETL causes silent financial reconciliation mismatches."},
      {"question_id":"etl_int_004","type":"mcq","question":"What does schema evolution handle in a data pipeline?","options":["Upgrading the database version","Adapting to added/removed columns or changed data types in the source data without crashing","Migrating from Postgres to MySQL","Changing the Airflow DAG structure"],"correct_answer":1,"explanation":"Schema evolution allows pipelines and storage formats (like Parquet or Delta Lake) to handle dynamic source changes automatically, such as a new column being added to a JSON payload.","difficulty_score":5,"time_seconds":60,"tags":["schema_evolution","data_formats","resilience"],"prerequisites":["etl_beg_001"],"common_mistakes":["Assuming source schemas never change"],"learning_resources":["https://docs.delta.io/latest/delta-batch.html#schema-evolution"],"real_world_context":"Schema evolution prevents 3 AM PagerDuty alerts when a frontend dev adds a tracking field."}
    ],
    "advanced": [
      {"question_id":"etl_adv_001","type":"scenario","question":"A real-time Kafka-to-S3 streaming pipeline outputs tiny 10KB files every second, causing S3 performance degradation (the 'small files problem'). Best solution?","options":["Delete the S3 files hourly","Increase Kafka partition count","Use a batching layer or write buffers (like Kafka Connect's Time/Size rotation) to flush larger 100MB+ files","Use CSV instead of Parquet"],"correct_answer":2,"explanation":"S3 and analytics engines (Athena/Spark) struggle with thousands of small files due to metadata overhead. Streaming pipelines must buffer data in memory/disk and flush larger chunks (hourly or 100MB+) to optimise downstream reads.","difficulty_score":8,"time_seconds":120,"tags":["small_files","S3","streaming","Kafka","optimisation"],"prerequisites":["etl_int_002"],"common_mistakes":["Failing to aggregate streaming data before object storage writes"],"learning_resources":["https://aws.amazon.com/blogs/big-data/seven-tips-for-using-s3-select/"],"real_world_context":"The 'small files problem' is the most common scaling bottleneck in cloud data lakes."},
      {"question_id":"etl_adv_002","type":"mcq","question":"In streaming, what is the difference between Event Time and Processing Time?","options":["Event time is in UTC; Processing time is local time","Event time is when the event occurred; Processing time is when the pipeline observed/processed it","No difference","Event time is for logs, Processing time is for metrics"],"correct_answer":1,"explanation":"Event time is the timestamp generated at the source (e.g. mobile app click). Processing time is when the stream processor evaluates it. Network delays mean processing time lags significantly behind event time.","difficulty_score":7,"time_seconds":90,"tags":["streaming","watermarks","event_time"],"prerequisites":["etl_adv_001"],"common_mistakes":["Aggregating windows by processing time resulting in inaccurate hourly metrics"],"learning_resources":["https://flink.apache.org/2015/12/11/introducing-stream-windows.html"],"real_world_context":"Handling out-of-order data using Event Time windows and Watermarks is critical in Flink/Spark Streaming."}
    ]
  }
}

spark_skill = {
  "skill_id": "apache_spark",
  "skill_name": "Apache Spark",
  "category": "data_engineering",
  "total_questions": 10,
  "levels": {
    "beginner": [
      {"question_id":"spk_beg_001","type":"mcq","question":"What does RDD stand for in Apache Spark?","options":["Relational Data Definition","Resilient Distributed Dataset","Random Data Distribution","Redundant Disk Data"],"correct_answer":1,"explanation":"RDDs are Spark's fundamental data structure: immutable, distributed collections of objects that can be computed across a cluster. They are resilient to node failures via lineage tracking.","difficulty_score":2,"time_seconds":30,"tags":["RDD","architecture","fundamentals"],"prerequisites":[],"common_mistakes":["Thinking RDDs are stored on a single node"],"learning_resources":["https://spark.apache.org/docs/latest/rdd-programming-guide.html"],"real_world_context":"While DataFrames are standard now, RDDs form the execution engine underneath."},
      {"question_id":"spk_beg_002","type":"true_false","question":"Spark DataFrames execute transformations lazily.","correct_answer":True,"explanation":"Transformations (like select, filter) do not compute immediately. They create a logical plan (lineage). Computation only triggers when an Action (like show, count, write) is called (lazy evaluation).","difficulty_score":2,"time_seconds":30,"tags":["lazy_evaluation","DataFrame","transformations"],"prerequisites":["spk_beg_001"],"common_mistakes":["Expect filter() to immediately scan data in memory"],"learning_resources":["https://spark.apache.org/docs/latest/rdd-programming-guide.html#rdd-operations"],"real_world_context":"Lazy evaluation allows Spark's Catalyst optimizer to reorder and optimise the entire query plan before any data scanning occurs."},
      {"question_id":"spk_beg_003","type":"mcq","question":"Which operation is an Action in Spark?","options":["filter()","groupBy()","count()","withColumn()"],"correct_answer":2,"explanation":"count() triggers execution across the cluster and returns a long integer to the driver program. filter, groupBy, and withColumn are Transformations that just build the DAG.","difficulty_score":2,"time_seconds":30,"tags":["actions","transformations","API"],"prerequisites":["spk_beg_002"],"common_mistakes":["Confusing transformations with actions"],"learning_resources":["https://spark.apache.org/docs/latest/rdd-programming-guide.html#actions"],"real_world_context":"Calling too many actions (like frequent `.show()` in loops) kills Spark performance."},
      {"question_id":"spk_beg_004","type":"true_false","question":"Spark strictly requires Hadoop to run.","correct_answer":False,"explanation":"Spark is a compute engine. It can run standalone, on Mesos, Kubernetes, or YARN (Hadoop's resource manager). It can read from S3, local files, or Cassandra, requiring zero Hadoop setup.","difficulty_score":2,"time_seconds":30,"tags":["deployment","Hadoop","architecture"],"prerequisites":[],"common_mistakes":["Assuming Spark and Hadoop are inseparable"],"learning_resources":["https://spark.apache.org/docs/latest/cluster-overview.html"],"real_world_context":"Most modern Spark workloads run on cloud object storage (S3) or Kubernetes, not HDFS."}
    ],
    "intermediate": [
      {"question_id":"spk_int_001","type":"scenario","question":"A Spark join between a 50GB table and a 5MB table is slow due to shuffling. What is the BEST optimisation?","options":["Increase spark.sql.shuffle.partitions","Use a Broadcast Join","Repartition both tables","Write to Parquet first"],"correct_answer":1,"explanation":"A Broadcast Join skips shuffling entirely by broadcasting the small 5MB table to every executor memory. The large table can then be read and joined locally without any data moving across the network.","difficulty_score":5,"time_seconds":60,"tags":["broadcast_join","shuffles","performance","optimisation"],"prerequisites":["spk_beg_002"],"common_mistakes":["Increasing shuffle partitions for small tables (causes small file problems)"],"learning_resources":["https://spark.apache.org/docs/latest/sql-performance-tuning.html"],"real_world_context":"Broadcast joins are the absolute most important Spark tuning mechanism for heavy ETL."},
      {"question_id":"spk_int_002","type":"mcq","question":"What causes a Data Skew OutOfMemory (OOM) error during a groupBy?","options":["The master node ran out of RAM","One executor received 90% of the data because a single key dominates the dataset, overwhelming its memory","Data was compressed too highly","Using RDD instead of DataFrame"],"correct_answer":1,"explanation":"When data is skewed (e.g. 90% of null IDs or one super-customer), hashing maps all those records to one partition/executor during the shuffle. That single executor processes gigabytes while others sit idle, causing OOM.","difficulty_score":6,"time_seconds":75,"tags":["data_skew","OOM","shuffles"],"prerequisites":["spk_beg_001"],"common_mistakes":["Increasing executor memory instead of salting keys"],"learning_resources":["https://www.databricks.com/glossary/data-skew"],"real_world_context":"Skewed joins/groupings are the #1 cause of random Spark job crashes."},
      {"question_id":"spk_int_003","type":"code_debugging","question":"Why does Spark recompute the entire CSV read and filter logic twice here?\n\n```python\ndf = spark.read.csv('huge.csv').filter(x)\nprint(df.count())\ndf.write.parquet('out')\n```","options":["Spark writes files synchronously","DataFrames are immutable","The DataFrame is not cached, so lazy evaluation re-executes the DAG from the source for each action","CSV reading implies recomputing"],"correct_answer":2,"explanation":"Because Spark is lazily evaluated, every Action (count, write) traverses the lineage from the source. To prevent re-reading the CSV, you must explicitly call `df.cache()` before the first action.","difficulty_score":6,"time_seconds":60,"tags":["caching","lineage","lazy_evaluation"],"prerequisites":["spk_beg_002"],"common_mistakes":["Assuming DataFrames are automatically stored in memory after creation"],"learning_resources":["https://spark.apache.org/docs/latest/rdd-programming-guide.html#rdd-persistence"],"real_world_context":"Unintentional recomputation doubles AWS compute bills on complex ETLs."},
      {"question_id":"spk_int_004","type":"mcq","question":"What does the Catalyst Optimizer do in Spark SQL?","options":["Translates RDD operations into low-level bytecode","Provides a UI for monitoring","Pushes down filters to the storage layer, reorders joins, and optimises logical query plans into physical plans","Manages executor memory allocation"],"correct_answer":2,"explanation":"Catalyst is Spark's query optimizer for DataFrames/SQL. It analyses the logical plan, applies optimizations (like filter pushdown and join reordering), and generates efficient physical execution plans.","difficulty_score":6,"time_seconds":60,"tags":["Catalyst","query_optimizer","Spark_SQL"],"prerequisites":["spk_beg_002"],"common_mistakes":["Thinking Catalyst manages memory (that's Project Tungsten)"],"learning_resources":["https://databricks.com/blog/2015/04/13/deep-dive-into-spark-sqls-catalyst-optimizer.html"],"real_world_context":"Catalyst allows Python/SQL Code to run as fast as Scala by optimising underneath."}
    ],
    "advanced": [
      {"question_id":"spk_adv_001","type":"scenario","question":"A Spark job processes 10,000 small 1MB files. It takes 20 minutes just to start tasks. What is the fundamental issue?","options":["Network bottleneck","Task scheduling and metadata overhead far exceeds the actual compute time for small files","Executors are too large","Shuffle partitions are set to 200"],"correct_answer":1,"explanation":"Reading thousands of small files creates thousands of tiny tasks. The Spark driver spends more time sending task instructions and negotiating metadata with S3 than executors spend processing data. Compacting files or using `spark.read.option('recursiveFileLookup')` can help.","difficulty_score":8,"time_seconds":90,"tags":["small_files","S3","driver_overhead","performance"],"prerequisites":["spk_int_002"],"common_mistakes":["Allocating larger executors to process small files faster"],"learning_resources":["https://www.databricks.com/blog/2015/05/28/tuning-java-garbage-collection-for-spark-applications.html"],"real_world_context":"S3 metadata listing operations for small files are an extremely common Spark bottleneck."},
      {"question_id":"spk_adv_002","type":"mcq","question":"How does 'Salting' resolve Spark data skew during a join?","options":["Encrypting the data","Adding a random integer prefix to the skewed join key, replicating the smaller table, to distribute processing across multiple partitions","Increasing spark.sql.autoBroadcastJoinThreshold","Caching the large table"],"correct_answer":1,"explanation":"Salting adds random numbers (0 to N) to the dominant key in the large table. The small table rows with that key are exploded (replicated) N times with the matching suffixes. This forces the shuffle to distribute the heavy key across N partitions.","difficulty_score":9,"time_seconds":120,"tags":["salting","data_skew","joins","advanced_tuning"],"prerequisites":["spk_int_002"],"common_mistakes":["Trying to use broadcast join on a 10GB table","Increasing executor counts"],"learning_resources":["https://towardsdatascience.com/managing-data-skew-in-apache-spark-1402324dc254"],"real_world_context":"Salting is the ultimate fallback technique when a key distribution is fundamentally broken in petabyte-scale joins."}
    ]
  }
}

dw_skill = {
  "skill_id": "data_warehousing",
  "skill_name": "Data Warehousing",
  "category": "data_engineering",
  "total_questions": 10,
  "levels": {
    "beginner": [
      {"question_id":"dw_beg_001","type":"mcq","question":"What is the difference between a fact table and a dimension table in a data warehouse?","options":["Fact tables store metadata; dimensions store transactions","Fact tables store measurable events/metrics; dimensions provide context","No difference","Fact tables are smaller than dimensions"],"correct_answer":1,"explanation":"Fact tables store quantitative metrics like sales amount or page views. Dimension tables provide descriptive context like product name or customer region. Facts reference dimensions via foreign keys.","difficulty_score":2,"time_seconds":30,"tags":["star_schema","fact_tables","dimension_tables"],"prerequisites":[],"common_mistakes":["Placing descriptive attributes in fact tables"],"learning_resources":["https://www.kimballgroup.com/"],"real_world_context":"Star schema design is the foundation of all dimensional data warehouse modelling."},
      {"question_id":"dw_beg_002","type":"mcq","question":"What does OLAP stand for?","options":["Online Analytical Processing","Online Application Protocol","Offline Logical Analysis Pipeline","Open Layered Architecture Platform"],"correct_answer":0,"explanation":"OLAP (Online Analytical Processing) supports complex analytical queries on large datasets, typically aggregating historical data. OLTP (Online Transaction Processing) handles high-volume insert/update transactional operations.","difficulty_score":1,"time_seconds":30,"tags":["OLAP","OLTP","fundamentals"],"prerequisites":[],"common_mistakes":["Confusing OLAP with OLTP workloads"],"learning_resources":["https://docs.microsoft.com/en-us/azure/architecture/data-guide/relational-data/online-analytical-processing"],"real_world_context":"BI tools like Tableau query OLAP systems (Snowflake, BigQuery, Redshift) for dashboards."},
      {"question_id":"dw_beg_003","type":"true_false","question":"A snowflake schema normalises dimension tables, whereas a star schema keeps them denormalised.","correct_answer":True,"explanation":"Star schema uses denormalised dimension tables (all attributes in one table). Snowflake schema normalises dimensions into multiple related tables, reducing redundancy but adding join complexity.","difficulty_score":3,"time_seconds":30,"tags":["star_schema","snowflake_schema","normalisation"],"prerequisites":["dw_beg_001"],"common_mistakes":["Confusing the two schemas"],"learning_resources":["https://www.kimballgroup.com/"],"real_world_context":"Star schema is preferred in most modern cloud data warehouses for query performance."},
      {"question_id":"dw_beg_004","type":"mcq","question":"Which SQL window function calculates a year-to-date total?","options":["GROUP BY with SUM","SUM OVER (ORDER BY date ROWS UNBOUNDED PRECEDING)","CUMULATIVE_SUM()","PARTITION BY year"],"correct_answer":1,"explanation":"SUM() OVER (PARTITION BY year ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) computes a running total from the start of the year to each row. This is the standard window function pattern for YTD metrics.","difficulty_score":3,"time_seconds":45,"tags":["window_functions","running_total","YTD","SQL"],"prerequisites":["dw_beg_001"],"common_mistakes":["Using GROUP BY which collapses rows instead of computing running total"],"learning_resources":["https://mode.com/sql-tutorial/sql-window-functions/"],"real_world_context":"YTD window functions power financial reporting dashboards."}
    ],
    "intermediate": [
      {"question_id":"dw_int_001","type":"scenario","question":"A Snowflake query scanning 5TB of data runs slowly. What is the FIRST optimisation to consider?","options":["Scale up warehouse size","Apply clustering keys or partition pruning via WHERE on date columns","Use a larger Snowflake edition","Compress all tables"],"correct_answer":1,"explanation":"Clustering keys allow Snowflake's micro-partition pruning to skip irrelevant partitions, reducing the data scanned. Scaling compute is expensive; always optimise data access patterns first.","difficulty_score":5,"time_seconds":75,"tags":["Snowflake","clustering","performance","partition_pruning"],"prerequisites":["dw_beg_001"],"common_mistakes":["Paying for larger warehouses before optimising queries"],"learning_resources":["https://docs.snowflake.com/en/user-guide/tables-clustering-intro.html"],"real_world_context":"Efficient clustering can reduce Snowflake query costs by 80%."},
      {"question_id":"dw_int_002","type":"mcq","question":"What is a materialised view in a data warehouse?","options":["A virtual table computed at query time","A pre-computed, stored query result that is periodically refreshed","A synonym for an index","A temporary table dropped after each session"],"correct_answer":1,"explanation":"Materialised views store the result of a query on disk and refresh periodically. They dramatically speed up expensive aggregations by pre-computing them. Unlike regular views, they occupy storage.","difficulty_score":5,"time_seconds":60,"tags":["materialised_views","performance","data_warehouse"],"prerequisites":["dw_int_001"],"common_mistakes":["Confusing materialised views with regular views"],"learning_resources":["https://docs.snowflake.com/en/user-guide/views-materialized.html"],"real_world_context":"Materialised views reduce BI dashboard query times from minutes to seconds."},
      {"question_id":"dw_int_003","type":"true_false","question":"BigQuery charges based on the amount of data SCANNED by a query, not rows returned.","correct_answer":True,"explanation":"BigQuery uses columnar storage and charges per byte scanned. Selecting only needed columns and partitioning tables reduces cost significantly. SELECT * is expensive as it scans all columns.","difficulty_score":5,"time_seconds":45,"tags":["BigQuery","pricing","columnar_storage","cost_optimisation"],"prerequisites":["dw_beg_002"],"common_mistakes":["Using SELECT * in BigQuery and receiving unexpected bills"],"learning_resources":["https://cloud.google.com/bigquery/pricing"],"real_world_context":"Column pruning and partition filters are essential for BigQuery cost management."},
      {"question_id":"dw_int_004","type":"mcq","question":"What is the purpose of a surrogate key in a data warehouse dimension?","options":["Natural business key from source system","System-generated integer key used internally for joins","Encryption key for sensitive data","Foreign key pointing to fact table"],"correct_answer":1,"explanation":"Surrogate keys are system-generated integers that uniquely identify dimension records. They are used instead of natural keys to handle SCD Type 2 history, source system changes, and join performance.","difficulty_score":5,"time_seconds":60,"tags":["surrogate_key","dimensional_modelling","SCD"],"prerequisites":["dw_beg_001"],"common_mistakes":["Using natural keys as primary keys causing SCD Type 2 issues"],"learning_resources":["https://www.kimballgroup.com/2006/01/surrogate-keys/"],"real_world_context":"Surrogate keys are required for handling SCD Type 2 history in dimension tables."}
    ],
    "advanced": [
      {"question_id":"dw_adv_001","type":"scenario","question":"A dbt model runs queries taking 45 minutes in production. What is the BEST dbt feature to address this for heavy aggregation models?","options":["Add more sources","Convert to an incremental model","Use dbt compile","Add more tests"],"correct_answer":1,"explanation":"dbt incremental models only process new/changed records since the last run, reducing transform time from 45 minutes to seconds for append-heavy tables. Full-refresh is only needed for historical corrections.","difficulty_score":8,"time_seconds":120,"tags":["dbt","incremental_models","performance","data_warehouse"],"prerequisites":["dw_int_002","dw_int_003"],"common_mistakes":["Running full-refresh models daily for append-only fact tables"],"learning_resources":["https://docs.getdbt.com/docs/build/incremental-models"],"real_world_context":"dbt incremental models are the standard for optimising large fact table transformations."},
      {"question_id":"dw_adv_002","type":"mcq","question":"What is the Kimball Bus Matrix used for?","options":["Monitoring data pipeline health","Documenting which business processes share conformed dimensions","Scheduling ETL jobs","Encrypting warehouse data"],"correct_answer":1,"explanation":"The Kimball Bus Matrix maps business processes (rows) to conformed dimensions (columns). It ensures different fact tables use the same dimension definitions, enabling cross-process analysis in a data warehouse.","difficulty_score":8,"time_seconds":120,"tags":["Kimball","bus_matrix","conformed_dimensions","dimensional_modelling"],"prerequisites":["dw_adv_001"],"common_mistakes":["Building siloed fact tables without conformed dimensions"],"learning_resources":["https://www.kimballgroup.com/data-warehouse-business-intelligence-resources/kimball-techniques/"],"real_world_context":"The Bus Matrix is the design artefact for enterprise data warehouse governance."}
    ]
  }
}

pandas_skill = {
  "skill_id": "pandas_numpy",
  "skill_name": "Pandas/NumPy",
  "category": "data_engineering",
  "total_questions": 8,
  "levels": {
    "beginner": [
      {"question_id":"pd_beg_001","type":"mcq","question":"Which pandas method shows the first 5 rows of a DataFrame?","options":["df.first()","df.head()","df.top()","df.show(5)"],"correct_answer":1,"explanation":"df.head() returns the first n rows (default 5). df.show() is a PySpark method. df.first() does not exist in pandas. df.head(n) accepts an optional count argument.","difficulty_score":1,"time_seconds":30,"tags":["pandas","basics","DataFrame"],"prerequisites":[],"common_mistakes":["Using show() which is PySpark not pandas"],"learning_resources":["https://pandas.pydata.org/"],"real_world_context":"head() is the first command for exploratory data analysis."},
      {"question_id":"pd_beg_002","type":"true_false","question":"In pandas, df['col'] and df.loc[:, 'col'] always return identical results.","correct_answer":False,"explanation":"df['col'] is shorthand and may return a copy or a view depending on context. df.loc[:, 'col'] is explicit and always returns a view for assignment operations. Chained indexing with df['col'][0] = x can cause SettingWithCopyWarning.","difficulty_score":3,"time_seconds":45,"tags":["pandas","loc","indexing","SettingWithCopyWarning"],"prerequisites":["pd_beg_001"],"common_mistakes":["Using chained indexing for assigning values"],"learning_resources":["https://pandas.pydata.org/docs/user_guide/indexing.html"],"real_world_context":"loc is preferred for assignment to avoid silent in-place modification errors."},
      {"question_id":"pd_beg_003","type":"mcq","question":"Which NumPy operation performs element-wise multiplication of two arrays?","options":["np.dot(a, b)","a * b","np.cross(a, b)","np.multiply_outer(a, b)"],"correct_answer":1,"explanation":"The * operator performs element-wise (Hadamard) multiplication on NumPy arrays. np.dot() performs dot product (matrix multiplication). a * b requires arrays to be broadcastable to the same shape.","difficulty_score":2,"time_seconds":30,"tags":["NumPy","array_operations","element_wise"],"prerequisites":[],"common_mistakes":["Confusing * (element-wise) with np.dot() (matrix multiply)"],"learning_resources":["https://numpy.org/"],"real_world_context":"Element-wise operations are fundamental to vectorised ML feature computation."}
    ],
    "intermediate": [
      {"question_id":"pd_int_001","type":"code_debugging","question":"This code modifies df1 unintentionally:\n\ndf2 = df1[df1['a'] > 0]\ndf2['b'] = 99\n\nWhy?","options":["df1 is a global variable","df2 is a view of df1; modifying df2 may modify df1","b column does not exist yet","Assignment to filtered DataFrame is unsupported"],"correct_answer":1,"explanation":"Filtering a DataFrame may return a view, not a copy. Assigning to a view can modify the original. Use df2 = df1[df1['a'] > 0].copy() to ensure df2 is an independent copy.","difficulty_score":5,"time_seconds":75,"tags":["pandas","copy_vs_view","SettingWithCopyWarning"],"prerequisites":["pd_beg_002"],"common_mistakes":["Not calling .copy() after filtering"],"learning_resources":["https://pandas.pydata.org/docs/user_guide/indexing.html"],"real_world_context":"View vs copy bugs cause silent data corruption in data transformation pipelines."},
      {"question_id":"pd_int_002","type":"mcq","question":"Which pandas method is the most performant for applying a function across a large DataFrame column?","options":["df.apply(func)","df['col'].map(func)","Vectorised NumPy operation","df.applymap(func)"],"correct_answer":2,"explanation":"Vectorised NumPy operations (e.g., df['col'] * 2) run in optimised C code and are 10-100x faster than apply() or map() which iterate in Python. Always prefer vectorisation for numeric operations.","difficulty_score":5,"time_seconds":60,"tags":["performance","vectorisation","pandas","NumPy"],"prerequisites":["pd_beg_003"],"common_mistakes":["Using apply() for simple arithmetic that can be vectorised"],"learning_resources":["https://pandas.pydata.org/docs/user_guide/enhancingperf.html"],"real_world_context":"Replacing apply() loops with vectorised ops is the most common pandas performance win."},
      {"question_id":"pd_int_003","type":"scenario","question":"You need to join two DataFrames on a column that has duplicates in both. What type of merge results?","options":["Inner join — duplicates dropped","Many-to-many join — cartesian product of matching rows","Error — pandas forbids duplicate keys","Left join only"],"correct_answer":1,"explanation":"A merge on columns with duplicates produces a many-to-many join — every combination of matching rows from both DataFrames. If left has 3 rows matching key=1 and right has 2, the result has 6 rows for that key.","difficulty_score":6,"time_seconds":75,"tags":["merge","many_to_many","joins","pandas"],"prerequisites":["pd_int_001"],"common_mistakes":["Not expecting row explosion from duplicate join keys"],"learning_resources":["https://pandas.pydata.org/docs/user_guide/merging.html"],"real_world_context":"Unexpected row explosion from duplicate keys is a common source of data quality issues."}
    ],
    "advanced": [
      {"question_id":"pd_adv_001","type":"scenario","question":"Processing a 50GB CSV with pandas on a 16GB machine crashes. What is the best Pandas-compatible approach before moving to Spark?","options":["Increase swap space","Use Dask for parallelised pandas-like API on chunked data","Use numpy.memmap","Compress the CSV"],"correct_answer":1,"explanation":"Dask provides a pandas-compatible API that parallelises operations across chunks of the file using lazy evaluation. It runs on a single machine or cluster and is the natural scale-up path before introducing Spark's complexity.","difficulty_score":7,"time_seconds":120,"tags":["Dask","large_data","pandas","scale"],"prerequisites":["pd_int_003"],"common_mistakes":["Jumping straight to Spark for data that fits in Dask"],"learning_resources":["https://docs.dask.org/"],"real_world_context":"Dask is the pragmatic middle ground between pandas and Spark for analytics at scale."},
      {"question_id":"pd_adv_002","type":"mcq","question":"What does NumPy broadcasting allow?","options":["Broadcasting arrays to multiple machines","Performing operations on arrays of different but compatible shapes without explicit loops","Sending data to GPUs","Parallel pandas operations"],"correct_answer":1,"explanation":"Broadcasting implicitly expands smaller arrays to match the shape of larger ones during operations, avoiding explicit loops or manual array replication. Shapes are compatible when dimensions are equal or one of them is 1.","difficulty_score":7,"time_seconds":90,"tags":["NumPy","broadcasting","vectorisation","shapes"],"prerequisites":["pd_beg_003"],"common_mistakes":["Not understanding shape compatibility rules for broadcasting"],"learning_resources":["https://numpy.org/doc/stable/user/basics.broadcasting.html"],"real_world_context":"Broadcasting is fundamental to efficient ML feature engineering and loss computation."}
    ]
  }
}

skills = [ts_skill, etl_skill, spark_skill, dw_skill, pandas_skill]
